### ISSUE TITLE
Handle Collector timeouts in BaseSearcher#getHits()

### ISSUE THREAD

**Issue by pablomendes** [dbpedia-spotlight/dbpedia-spotlight#10]
Converted from [SourceForge issue 3317379](http://sourceforge.net/support/tracker.php?aid=3317379), submitted by jodaiber

TimeLimitingCollector should be added to BaseSearcher to limit slow queries. However, with the current version of Lucene most queries will fail with this collector.

The problem may be resolved by using a newer version of Lucene, see 
http://www.gossamer-threads.com/lists/lucene/java-dev/93855?do=post_view_flat#93855

**Comment by sandroacoelho** [comment]
This issue is not valid anymore. We will replace Lucene in a new version.
