### ISSUE TITLE
LingPipeSpotter and punctuation

### ISSUE THREAD

**Issue by pablomendes** [dbpedia-spotlight/dbpedia-spotlight#12]
Converted from [SourceForge issue 3423827](http://sourceforge.net/support/tracker.php?aid=3423827), submitted by pablomendes

LingPipeSpotter fails when surface form appears attached to punctuation.

e.g. if "the virus" is in dictionary, then "the virus." is not spotted. Similarly for 
KELLER+KELLER
William Black,
now-familiar
Meltdown:
BIG BOYS'
high-cost-of-labor problem

Presumably can be solved in org.dbpedia.spotlight.spot.lingpipe.AnnotationTokenizerFactory

outstanding credit-card debt—much

**Comment by sandroacoelho** [comment]
This issue is not valid anymore. We will replace Lucene in a new version.
