### ISSUE TITLE
Set prior in TwoStep

### ISSUE THREAD

**Issue by pablomendes** [dbpedia-spotlight/dbpedia-spotlight#15]
Converted from [SourceForge issue 3428146](http://sourceforge.net/support/tracker.php?aid=3428146), submitted by nobody

The "Document" disambiguator is producing prior = 0 for everybody. If you change to Occurrences, you will see prior values for all the candidates.

**Comment by sandroacoelho** [comment]
This issue is not valid anymore. We will replace Lucene in a new version.
