### ISSUE TITLE
ExtractOccsFromWikipedia filters URL-encoded resources

### ISSUE THREAD

**Issue by pablomendes** [dbpedia-spotlight/dbpedia-spotlight#16]
Converted from [SourceForge issue 3518698](http://sourceforge.net/support/tracker.php?aid=3518698), submitted by rschwab

I have tried to build indices for German, but i have not found resources there, which contain german umlaute, such as Österreich, München or Völkerrecht.
Investigating what may be the reason i have identified the UriWhitelistFilter to filter the uris for these resources,
because the resource uris are url encoded and the values in conceptURIs.list are not, which are used to build the UriWhitelistFilter.

reinhard@thord:>head conceptURIs.list
Anschluss_(Soziologie)
Alan_Smithee
Actinium
Aussagenlogik
Ang_Lee
Anthony_Minghella
US-amerikanischer_Film
Vorsätze_für_Maßeinheiten
Achsensprung_(Film)
ISO_4217

reinhard@thord:>grep -i Österreich conceptURIs.list | wc -l
1940

reinhard@thord:>grep -i München conceptURIs.list | wc -l
767

**Comment by sandroacoelho** [comment]
This bug was fixed.

![luke-lucene](https://www.dropbox.com/s/h2yiag19fhbbogm/resources.png?raw=1)


If you want to build new models for Lucene, please follow the instructions in this [repo](https://github.com/sandroacoelho/lucene-quickstarter)
