### ISSUE TITLE
FieldLength is limited to 25000 in BaseIndexer

### ISSUE THREAD

**Issue by pablomendes** [dbpedia-spotlight/dbpedia-spotlight#17]
Converted from [SourceForge issue 3518711](http://sourceforge.net/support/tracker.php?aid=3518711), submitted by rschwab

In BaseIndexer i have found this initialization of the IndexWriter 

this.mWriter = new IndexWriter(lucene.directory(),
                                       lucene.defaultAnalyzer(),
                                       create,
                                       new IndexWriter.MaxFieldLength(25000));

i think this can be a problem for disambiguation of resources which have a big support like Austria, which have many occurences/contexts.
i have used the explain feature of lucene to give me explanations about the ranking of resources, when retrieving 
the candidates for a surface form with text, eg for "Austria is a country.", surface form is "Austria".
the explanation tells me, that the term frequency for austria is low, some hundreds, despite the support of more than
25000.
the resource "Austria" is the worst ranked candidate what i would not have expected as it is the most popular resource
having this surface form.

**Comment by sandroacoelho** [comment]
This issue is not valid anymore. We will replace Lucene in a new version.
