### ISSUE TITLE
Analyzer ignored when adding surface forms, types and...

### ISSUE THREAD

**Issue by pablomendes** [dbpedia-spotlight/dbpedia-spotlight#18]
Converted from [SourceForge issue 3518730](http://sourceforge.net/support/tracker.php?aid=3518730), submitted by rschwab

The analyzer configuration in indexing.properties seems to be ignored,
when i proceed with adding surface forms, adding types and compressing the index.
I use the Snowball Anaylzer for English and German,
stemming and filtering stop words are done as expected when indexing the occurrences.
But when i add surface forms, types or compress the index, stemming disappears,
and stop words appear.

**Comment by sandroacoelho** [comment]
This issue is not valid anymore. We will replace Lucene in a new version.
