### ISSUE TITLE
[Feature] Timeout for Multithreaded Disamb

### ISSUE THREAD

**Issue by pablomendes** [dbpedia-spotlight/dbpedia-spotlight#19]
Converted from [SourceForge issue 3305032](http://sourceforge.net/support/tracker.php?aid=3305032), submitted by pablomendes

Class: DefaultDisambiguator
Parameter: Timeout for each disambiguation and for aggregating all disambiguations

**Comment by sandroacoelho** [comment]
This issue is not valid anymore. We will replace Lucene in a new version.
