### ISSUE TITLE
Inconsistent results when using org.dbpedia.spotlight.candidateMap.dir 

### ISSUE THREAD

**Issue by sangv** [dbpedia-spotlight/dbpedia-spotlight#195]
During my testing, I came across some inconsistent results. Testing each configuration, it has come down to this: Using org.dbpedia.spotlight.candidateMap.dir with the data extracted from http://spotlight.dbpedia.org/download/release-0.5/candidate-index-full.tgz leads to inconsistent behavior.

I have tried using both lucene and jdbm backend.

Way to replicate:

I) Send a paragraph to the /annotate api. My results are consistent (meaning I get the same named entities for multiple requests with the same text)

ii) Send another paragraph that does not have any named entities. Now the json response I get has no resources. This is the expected behavior. On the server side however, the memory utilization goes up even if the passed in text is small.

iii) Send the same text I used in step i. This time I get no dbpedia resources. If I restart server and send the same request, I get the correct response. Everything works consistently as long as I send the request with named entities but behavior is inconsistent if I change the request.

If I completely comment out the org.dbpedia.spotlight.candidateMap.dir configuration (meaning it uses actual index for the candidate map as well), then the behavior is consistent albeit quite slow.

Also, is there any caching based on request ip that causes this issue.

**Comment by sandroacoelho** [comment]
Hi,

We have moved Lucene to a new repository, supporting Spotlight approaches by repo.
If this problem persists, please open it again in the respective repository. 

Thank you for collaborate with DBpedia community.
