### ISSUE TITLE
[Feature] WADL URI

### ISSUE THREAD

**Issue by pablomendes** [dbpedia-spotlight/dbpedia-spotlight#21]
Converted from [SourceForge issue 3305039](http://sourceforge.net/support/tracker.php?aid=3305039), submitted by pablomendes

Make URI configurable in org.dbpedia.spotlight.web.rest.wadl.ExternalUriWadlGeneratorConfig

**Comment by sandroacoelho** [comment]
This issue is not valid anymore. We will replace Lucene in a new version.
