### ISSUE TITLE
[Feature] /candidates/?verbose=on filtering

### ISSUE THREAD

**Issue by pablomendes** [dbpedia-spotlight/dbpedia-spotlight#22]
Converted from [SourceForge issue 3305096](http://sourceforge.net/support/tracker.php?aid=3305096), submitted by pablomendes

The best debugging tool would allow us to see all parts of the process. For now I think the /candidates already takes care of the most important part. 

But in the future I foresee a ?mode=verbose or something like that. It would show also stuff that we threw out.
It would then list all surface forms spotted with the reason that they were thrown out if they were, then show all the possible disambiguations also with scores to allow full debugging.

```
<annotation>
  <annotatedText>Pablo ate one Apple.</annotatedText>
  <spots>
    <surfaceForm visibility="false" name="Pablo">
       <candidate label="Pablo Neruda" about="dbpedia:Pablo_Neruda visibility=false filters="ContextFilter" contextualScore="" priorScore="" finalScore=""/> 
       <candidate label="Pablo Picasso" about="dbpedia:Pablo_Picasso visibility=false filters="ContextFilter" contextualScore="" priorScore="" finalScore=""/>
      </surfaceForm> 
      <surfaceForm visibility="false" filters="AtLeastOneNounFilter">ate</a>
      <surfaceForm visibility="false" filters="AtLeastOneNounFilter">one</a>
      <surfaceForm visibility="true" filters="" name="Apple">
         <candidate label="Apple Computers" about="dbpedia:Apple_Inc." visibility=true filters=""  contextualScore="" priorScore="" finalScore=""/>
         .....
  </spots>
</annotation>
```

**Comment by sandroacoelho** [comment]
This issue is not valid anymore. We will replace Lucene in a new version.
