### ISSUE TITLE
Hugo Silva

### ISSUE THREAD

**Issue by HugoFSilva** [dbpedia-spotlight/dbpedia-spotlight#231]
Good afternoon,

I'm installing a mirror of the web service of the DBPedia, so i'm trying to generate nerd_stats_output.tsv from nerd-stats.pig.

I've installed pig and when i run pig -x local nerd-stats.pig it gives me an error of the parameter LANG inside the script. The problem is that i dont know what to put in  the parameter. 

Can you help me? It's urgent.

Thank you.

**Comment by sandroacoelho** [comment]
Hi @HugoFSilva. 

Have you still need help? If yes, let me know just reopening the issue.

Thanks and sorry for the big delay
