### ISSUE TITLE
Italian DBpedia indexing error - MalformedInputException 

### ISSUE THREAD

**Issue by stefanoabbate** [dbpedia-spotlight/dbpedia-spotlight#233]
Dear all:

I noticed there have been important code changes in the past few months. What I am trying to do is the indexing of the Italian DBpedia. I have followed the steps but I get a `java.nio.charset.MalformedInputException: Input length = 1` when I try to execute the first step of `index.sh` `mvn scala:run -Dlauncher=ExtractCandidateMap "-DjavaOpts.Xmx=$JAVA_XMX" "-DaddArgs=$INDEX_CONFIG_FILE"`.

The complete error is the following:

`[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building DBpedia Spotlight Indexing 0.6
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] >>> scala-maven-plugin:3.1.5:run (default-cli) @ index >>>
[INFO] 
[INFO] --- maven-enforcer-plugin:1.2:enforce (enforce-maven-3) @ index ---
[INFO] 
[INFO] --- maven-enforcer-plugin:1.2:enforce (enforce-java-newer-6) @ index ---
[INFO] 
[INFO] --- maven-resources-plugin:2.3:resources (default-resources) @ index ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /home/stefano/dbpedia-spotlight/index/src/main/resources
[INFO] 
[INFO] --- scala-maven-plugin:3.1.5:add-source (scala-compile-first) @ index ---
[INFO] Add Source directory: /home/stefano/dbpedia-spotlight/index/src/main/scala
[INFO] Add Test Source directory: /home/stefano/dbpedia-spotlight/index/src/test/scala
[INFO] 
[INFO] --- scala-maven-plugin:3.1.5:compile (scala-compile-first) @ index ---
[WARNING]  Expected all dependencies to require Scala version: 2.9.2
[WARNING]  net.liftweb:lift-json_2.9.2:2.5-M1 requires scala version: 2.9.2
[WARNING]  net.liftweb:lift-json_2.9.2:2.5-M1 requires scala version: 2.9.2
[WARNING]  org.scala-lang:scalap:2.9.2 requires scala version: 2.9.2
[WARNING]  org.scalatest:scalatest_2.9.2:2.0.M4 requires scala version: 2.9.2
[WARNING]  org.scalaz:scalaz-core_2.9.2:6.0.4 requires scala version: 2.9.2
[WARNING]  org.scalanlp:breeze-math_2.9.2:0.1 requires scala version: 2.9.2
[WARNING]  org.scalanlp:breeze-process_2.9.2:0.1 requires scala version: 2.9.2
[WARNING]  org.scalanlp:breeze-learn_2.9.2:0.1 requires scala version: 2.9.2
[WARNING]  com.codecommit:anti-xml_2.9.1:0.3 requires scala version: 2.9.1
[WARNING] Multiple versions of scala libraries detected!
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ index ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- maven-resources-plugin:2.3:testResources (default-testResources) @ index ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /home/stefano/dbpedia-spotlight/index/src/test/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ index ---
[INFO] No sources to compile
[INFO] 
[INFO] <<< scala-maven-plugin:3.1.5:run (default-cli) @ index <<<
[INFO] 
[INFO] --- scala-maven-plugin:3.1.5:run (default-cli) @ index ---
[WARNING]  Expected all dependencies to require Scala version: 2.9.2
[WARNING]  net.liftweb:lift-json_2.9.2:2.5-M1 requires scala version: 2.9.2
[WARNING]  net.liftweb:lift-json_2.9.2:2.5-M1 requires scala version: 2.9.2
[WARNING]  org.scala-lang:scalap:2.9.2 requires scala version: 2.9.2
[WARNING]  org.scalatest:scalatest_2.9.2:2.0.M4 requires scala version: 2.9.2
[WARNING]  org.scalaz:scalaz-core_2.9.2:6.0.4 requires scala version: 2.9.2
[WARNING]  org.scalanlp:breeze-math_2.9.2:0.1 requires scala version: 2.9.2
[WARNING]  org.scalanlp:breeze-process_2.9.2:0.1 requires scala version: 2.9.2
[WARNING]  org.scalanlp:breeze-learn_2.9.2:0.1 requires scala version: 2.9.2
[WARNING]  com.codecommit:anti-xml_2.9.1:0.3 requires scala version: 2.9.1
[WARNING] Multiple versions of scala libraries detected!
[INFO] launcher 'ExtractCandidateMap' selected => org.dbpedia.spotlight.util.ExtractCandidateMap
 INFO 2013-10-01 17:05:49,506 main [IndexingConfiguration] - Loading configuration file ../conf/indexing.properties
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at scala_maven_executions.MainHelper.runMain(MainHelper.java:164)
	at scala_maven_executions.MainWithArgsInFile.main(MainWithArgsInFile.java:26)
Caused by: java.nio.charset.MalformedInputException: Input length = 1
	at java.nio.charset.CoderResult.throwException(CoderResult.java:277)
	at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:338)
	at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:177)
	at java.io.InputStreamReader.read(InputStreamReader.java:184)
	at java.io.BufferedReader.fill(BufferedReader.java:154)
	at java.io.BufferedReader.readLine(BufferedReader.java:317)
	at java.io.BufferedReader.readLine(BufferedReader.java:382)
	at scala.io.BufferedSource$BufferedLineIterator.hasNext(BufferedSource.scala:67)
	at scala.collection.Iterator$class.foreach(Iterator.scala:772)
	at scala.io.BufferedSource$BufferedLineIterator.foreach(BufferedSource.scala:43)
	at scala.collection.TraversableOnce$class.foldLeft(TraversableOnce.scala:143)
	at scala.io.BufferedSource$BufferedLineIterator.foldLeft(BufferedSource.scala:43)
	at scala.collection.TraversableOnce$class.$div$colon(TraversableOnce.scala:137)
	at scala.io.BufferedSource$BufferedLineIterator.$div$colon(BufferedSource.scala:43)
	at scala.collection.SetLike$class.$plus$plus(SetLike.scala:128)
	at scala.collection.immutable.Set$EmptySet$.$plus$plus(Set.scala:52)
	at scala.collection.TraversableOnce$class.toSet(TraversableOnce.scala:252)
	at scala.io.BufferedSource$BufferedLineIterator.toSet(BufferedSource.scala:43)
	at org.dbpedia.spotlight.util.ExtractCandidateMap$.main(ExtractCandidateMap.scala:411)
	at org.dbpedia.spotlight.util.ExtractCandidateMap.main(ExtractCandidateMap.scala)
	... 6 more
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 6.668s
[INFO] Finished at: Tue Oct 01 17:05:49 CEST 2013
[INFO] Final Memory: 15M/127M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal net.alchim31.maven:scala-maven-plugin:3.1.5:run (default-cli) on project index: wrap: org.apache.commons.exec.ExecuteException: Process exited with an error: 240 (Exit value: 240) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException`

Any hints? I have installed Java JDK 1.7, maven 3.0.4.

Same problem with both Ubuntu 12.04 and Debian 7.1 installed from scratch (using VMware).

Thanks!

Stefano

**Comment by sandroacoelho** [comment]
Hi @stefanoabbate 


This issue was solved and I have success to create the models in the following languages: german , greek , english, spanish, french , italian, dutch, polish, portuguese and russian.

You have now two options ready to use :

For the statistical backend, please follow [these instructions](https://github.com/dbpedia-spotlight/model-quickstarter)

For Lucene, please follow [these] (https://github.com/sandroacoelho/lucene-quickstarter)

Best,
