### ISSUE TITLE
AnnotationClientScala

### ISSUE THREAD

**Issue by pablomendes** [dbpedia-spotlight/dbpedia-spotlight#239]
We should remove "Scala" from the names of AnnotationClientScala, DBpediaSpotlightClientScala, etc.

DBpediaSpotlightClient.java should be brought back to life. (It serves as an example of how to write a client in Java for our system)

For all the other clients that were converted to scala, we only need the scala version. 

(cc @accardoso)

**Comment by medrokaimi** [comment]
I got this error
AnnotationClient cannot be resolved to a type
