### ISSUE TITLE
[Feature] Index configuration into index

### ISSUE THREAD

**Issue by pablomendes** [dbpedia-spotlight/dbpedia-spotlight#24]
Converted from [SourceForge issue 3306344](http://sourceforge.net/support/tracker.php?aid=3306344), submitted by pablomendes

Tracking which version of the code generated the index starts to get problematic, since we can now have compact index (where some fields are not stored).
We need a way to track parameters, so I suggest creating a "config document" in the index that contains the following fields:
- ANALYZER
- SIMILARITY
- SIMILARITY_THRESHOLDS
- DBPEDIA_SPOTLIGHT_VERSION
- MERGED (yes,no)
  This document will be read at startup and can be used by classes to test if they read the correct index, to see if some operations are legal, etc.

**Comment by sandroacoelho** [comment]
This issue is not valid anymore. We will replace Lucene in a new version.
