### ISSUE TITLE
[Feature] Wrapper classes for policies

### ISSUE THREAD

**Issue by pablomendes** [dbpedia-spotlight/dbpedia-spotlight#27]
Converted from [SourceForge issue 3314658](http://sourceforge.net/support/tracker.php?aid=3314658), submitted by pablomendes

We have developed a few ways to perform spot selection, and a few others to perform disambiguation. We provide DefaultDisambiguator and DefaultAnnotator as a default policy (with the results we like best). But many others could be created, to make it easier for users to just assemble their own solution from our parts. We already started providing wrapper classes for the spot selection (see interface Selector), and we should do the same for the disambiguators, and later for candidate selectors.

Inside EvaluateDisambiguation there are already a bunch of factory methods that would be better wrapped as Disambiguator classes and created from a DisambiguationFactory class.

**Comment by sandroacoelho** [comment]
This issue is not valid anymore. We will replace Lucene in a new version.
