### ISSUE TITLE
Creating/Updating FAQ 

### ISSUE THREAD

**Issue by dav009** [dbpedia-spotlight/dbpedia-spotlight#317]
So the questions in issues and the mailing list seem quite repetitive. 
I have gathered a few of them and want to update the wiki.

So far I have gathered this:
 - What are the difference between statistical and lucene?
 - What are the differences in the models available? what does "en_2+2" stands for?
 - How can I get json/xml/html from the annotate endpoint ?
 - Key differences between 0.6 and 0.7
 - I'm getting weird stuff ( mention the `coreferenceResolution` issue, and other ones (?) )
 - I'm getting different results from the demo, why?
Any suggestion  on what to add to the wiki?

**Comment by sjuyal** [comment]
@dav009  Is there any work been done regarding this. Because definitely I felt the importance of FAQ page while understanding some of the concepts. If not I would like to document some of the above questions. Also Glossary needs to be updated. Maybe we can move some of the definition related FAQs to glossary section of wiki.

**Comment by dav009** [comment]
Hi Sjuyal,
I've not done much about this.

Feel free to update it on the go. Poke me for the questions you cant find any answers around the wiki :)

**Comment by sjuyal** [comment]
@dav009 updated the FAQ with basic questions. please check [FAQ](https://github.com/dbpedia-spotlight/dbpedia-spotlight/wiki/FAQ) . You can help me with the question about 'models'. Also I guess a link can be created in the wiki page for FAQ (for easy access)

**Comment by dav009** [comment]
@sjuyal great!
On the model question: 

the numbers in the model names stand for cut-offs in terms of counts, so 2+3 stands for:  `minimum count of a surface form`=2, `minimum count of a context word`=3.
Higher minimum counts mean that more sf-entity and sf-context word combinations are left out of the model.

**Comment by sjuyal** [comment]
Thanks. Updated !

**Comment by dav009** [comment]
:) maybe it would be good to have a link to the FAQ on the README?

**Comment by sjuyal** [comment]
Done ! Created a PR after doing the changes :)
