### ISSUE TITLE
missing types (in statistical-backend data)

### ISSUE THREAD

**Issue by benzitohhh** [dbpedia-spotlight/dbpedia-spotlight#339]
In the statistical-backend data, some resources contain types ok. For example "Aspirin" (http://dbpedia.org/resource/Aspirin):
curl 'http://spotlight.sztaki.hu:2222/rest/annotate?text=Aspirin&confidence=0' -H 'Accept: application/json'
---->  "@types": "DBpedia:Drug"

But some resources are missing types. For example "Atorvastatin" (http://dbpedia.org/resource/Atorvastatin):
curl 'http://spotlight.sztaki.hu:2222/rest/annotate?text=Atorvastatin&confidence=0' -H 'Accept: application/json'
----> "@types": ""

In the above example, why is no type returned? (i.e. the dbpedia page shows that Atorvastatin has type Drug). Is this a problem with the model data? And if so, if I recreate data locally, would it help?

**Comment by dav009** [comment]
@benzitohhh It seems that the ResourceStore also contains the types of entities.
My guess would be that maybe at the time the spotlight models were built this type was not associated to this entity.
I will give it a check

**Comment by dav009** [comment]
http://spotlight.sztaki.hu:2222/rest/candidates/?confidence=0.2&support=20&text=Atorvastatin

shows that :
```
<resource label="Atorvastatin" uri="Atorvastatin" contextualScore="0.999965885344992" percentageOfSecondRank="0.0" support="107" priorScore="8.900283766000527E-7" finalScore="0.9999996604977363" types=""/>
```
No types :(

I think if you recreate the models using a fresh dbpedia-dump it should be alright

**Comment by benzitohhh** [comment]
ok thanks - really appreciated - will give it a shot!

**Comment by dav009** [comment]
@benzitohhh  I tried to look for some Dbpedia metadata to check whether the type existed before the model was created. Sadly I couldn't find any metadata on this.

**Comment by benzitohhh** [comment]
@dav009 Cool no worries, thanks for checking

**Comment by benzitohhh** [comment]
@dav009 Recreating the model fixed the problem. Thanks!
