### ISSUE TITLE
Problem in greek dbpedia spotlight

### ISSUE THREAD

**Issue by pkater** [dbpedia-spotlight/dbpedia-spotlight#341]
I failed to build from the sources the greek version of DBPedia Spotlight. I am getting the following:

DBpedia Spotlight annotation framework (parent POM) SUCCESS [1.591s]
DBpedia Spotlight Core ............................ SUCCESS [39.076s]
DBpedia Spotlight RESTful API ..................... FAILURE [1:03.906s]
DBpedia Spotlight Indexing ........................ SKIPPED
DBpedia Spotlight Evaluation ...................... SKIPPED

Failed to execute goal on project rest: Could not resolve dependencies for project org.dbpedia.spotlight:rest:jar:0.6: Failed to collect dependencies for [org.dbpedia.spotlight:core:jar:0.6 (compile), com.sun.jersey:jersey-bundle:jar:1.10 (compile), com.sun.jersey:jersey-server:jar:1.10 (compile), com.sun.jersey:jersey-client:jar:1.10 (compile), com.sun.jersey:jersey-grizzly:jar:1.10 (compile), com.sun.grizzly:grizzly-servlet-webserver:jar:1.9.48 (compile), xom:xom:jar:1.2.5 (compile), xerces:xmlParserAPIs:jar:2.6.2 (compile), xml-apis:xml-apis:jar:1.0.b2 (compile), net.sf.json-lib:json-lib:jar:jdk15:2.4 (compile), com.thoughtworks.xstream:xstream:jar:1.3.1 (compile), org.codehaus.jettison:jettison:jar:1.3 (compile), stax:stax-api:jar:1.0.1 (compile), de.l3s.boilerpipe:boilerpipe:jar:1.1.0 (compile), org.apache.any23:apache-any23-core:jar:0.7.0-incubating (compile), org.scala-lang:scala-compiler:jar:2.9.2 (provided), org.scala-lang:scala-library:jar:2.9.2 (compile)]: Failed to read artifact descriptor for org.openrdf.sesame:sesame-rio-trix:jar:2.6.1: Could not transfer artifact org.openrdf.sesame:sesame-rio-trix:pom:2.6.1 from/to aduna-software-release-repo (http://repo.aduna-software.org/maven2/releases): Connection to http://repo.aduna-software.org refused: Connection timed out 

Could somebody help me with this?
K.

**Comment by tgalery** [comment]
It looks like you are compiling an old version of spotlight, v 0.6, have you tried pulling the latest source code from master and building from scratch ?

**Comment by pkater** [comment]
Yes, it works for the master but I need the branch with the greek version of DBpedia Spotlight https://github.com/iavraam/dbpedia-spotlight.

**Comment by tgalery** [comment]
Hi pkater, I took a look at that version and is it almost 400 commits behind master. Theoretically spotlight is language agnostic, so if you don't need special tokenizers for greek, you could try to generate an entity-mention model for greek and run the version in master here with it.

**Comment by dav009** [comment]
taking a look at one of the branches( [dbpediaSpotlight_el](https://github.com/iavraam/dbpedia-spotlight/commits/dbpediaSpotlight_el)  ) it seems to fix some issues regarding unicode ?, it would have been good to merge them at its moment with master, but given all changes made from 0.6 until now, it is unclear whether they are still issues or not.

Worth giving a try using 0.7 and create a model for greek and run it to see if any weird encoding issue takes place.

**Comment by tgalery** [comment]
you can check out https://github.com/dbpedia-spotlight/model-quickstarter
and https://github.com/dbpedia-spotlight/pignlproc . I don't think the model quickstarter repo has a list of stopwords for greek, so i think that is the only thing you need, you might also consider using opennlp tokenizers and ner extractors for greek

**Comment by jodaiber** [comment]
I think all the Greek fixes were related to the Lucene version. It should be much easier (and better) to generate a statistical version for Greek (it's probably small enough to run without Hadoop). There shouldn't be any encoding issues (e.g. we had other non-Latin alphabet languages like Russian).

**Comment by sandroacoelho** [comment]
Hi @pkater,

First, you must sync/rebase your branch with our repo (git pull --rebase git://github.com/dbpedia-spotlight/dbpedia-spotlight.git)

And then you can build the Greek models

For JDBM, please follow [these instructions](https://github.com/dbpedia-spotlight/model-quickstarter)

For Lucene, please follow [these] (https://github.com/sandroacoelho/lucene-quickstarter)

If you have some issue related, please open a new one or reopen this issue.

Thanks
