### ISSUE TITLE
spotting miss

### ISSUE THREAD

**Issue by benzitohhh** [dbpedia-spotlight/dbpedia-spotlight#343]
Spotting for surface-form "active noise reduction" fails.

Specifically, some sub-surface-forms are matched (i.e. "active noise", "noise reduction"). But the full surface form is missing:

```
curl "http://spotlight.sztaki.hu:2222/rest/candidates?text=active+noise+reduction&confidence=0&support=0"
```

```
<annotation text="active noise reduction">
  <surfaceForm name="active noise" offset="0">
    <resource label="Active noise control" uri="Active_noise_control" contextualScore="0.9999935571455051" percentageOfSecondRank="0.0" support="64" priorScore="5.323534215177885E-7" finalScore="0.999999999945743" types=""/>
  </surfaceForm>
  <surfaceForm name="noise reduction" offset="7">
    <resource label="Noise reduction" uri="Noise_reduction" contextualScore="0.4321889916859049" percentageOfSecondRank="0.00364618821007759" support="229" priorScore="1.904827086368337E-6" finalScore="0.995844271565088" types=""/>
    <resource label="Dolby noise-reduction system" uri="Dolby_noise-reduction_system" contextualScore="0.4832492025249131" percentageOfSecondRank="0.12207095042571947" support="115" priorScore="9.565725542897762E-7" finalScore="0.00363103564205393" types=""/>
    <resource label="Noise control" uri="Noise_control" contextualScore="0.03261504464489923" percentageOfSecondRank="0.18375618037787775" support="104" priorScore="8.650743099664063E-7" finalScore="4.4324397185518575E-4" types=""/>
    <resource label="Quiet PC" uri="Quiet_PC" contextualScore="0.05194120556560536" percentageOfSecondRank="0.0" support="24" priorScore="1.996325330691707E-7" finalScore="8.144881924362847E-5" types=""/>
  </surfaceForm>
</annotation>
```

Any ideas why this is happening?

i.e. "active noise reduction" has a redirect page http://en.wikipedia.org/wiki/Active_noise_reduction . So it should be included in the model, right?

Strangely, "active noise control" is spotted fine:

```
curl "http://spotlight.sztaki.hu:2222/rest/candidates?text=active+noise+control&confidence=0&support=0"
```

```
<annotation text="active noise control">
  <surfaceForm name="active noise control" offset="0">
    <resource label="Active noise control" uri="Active_noise_control" contextualScore="0.9999714020162859" percentageOfSecondRank="0.0" support="64" priorScore="5.323534215177885E-7" finalScore="0.9999999999999929" types=""/>
  </surfaceForm>
</annotation>
```

Any help really appreciated!

Thanks,
Ben

**Comment by tgalery** [comment]
Hi @benzitohhh, if "active noise reduction" links to a page that redirects to `Active_noise_control` it means that this surface form is associated to the final page of the redirect chain.  Note that, in principle, this is how the system should work. If you send the text to the annotate endpoint do you get  `Active_noise_control` ?

**Comment by benzitohhh** [comment]
Hi @tgalery,

well.... sending "active noise reduction" to the annotate endpoint does indeed give "Active_noise_control". But it gives it for surface form "active noise", not "active noise reduction".

```
curl "http://spotlight.sztaki.hu:2222/rest/candidates?text=active+noise+reduction&confidence=0&support=0"
```

```
<a href="http://dbpedia.org/resource/Active_noise_control" title="http://dbpedia.org/resource/Active_noise_control" target="_blank">active nois<a href="http://dbpedia.org/resource/Noise_reduction" title="http://dbpedia.org/resource/Noise_reduction" target="_blank">noise reduction</a>
```

As mentioned before, "active noise reduction" does not appear in the candidates response either.

Why is the full surface form ("active noise reduction") missing from the candidates/annotation responses? 

Could it be that "active noise reduction" is missing from the model? Is there a way that I can check?

**Comment by benzitohhh** [comment]
@tgalery  - perhaps the broader question is.... how are "redirects" used in the spotlight statistical model? Are they treated the same way as disambigations/wikilinks (to form an occurance (s, e, c))?

Specifically in my case, "active noise reduction" has a redirect, but no disambiguations/wikilinks. Should it  be recognised as a surface form?

**Comment by dav009** [comment]
@benzitohhh maybe:
 - `active noise reduction` is not in the SurfaceForm store( maybe it was the first place never linked via that anchor in the corpora?) 
 - `active noise reduction`  is in the store but got a very low probability ( as the spotter usually prefers longer Surface forms )
 - Less likely but still possible a problem with the spotter.

I will check the store and let you know

**Comment by dav009** [comment]
Sorry for the delay.

`active noise reduction` nor `Active Noise Reduction` exists in the surface form store.
my guess is that it was never linked with that anchor in the wikipedia corpus.

**Comment by benzitohhh** [comment]
@dav009 ok thanks for checking - much appreciated

**Comment by dav009** [comment]
@benzitohhh  I will close this issue.

If you are using spotlight for a custom domain/area you can customize your models using : https://github.com/idio/spotlight-model-editor

You could potentially capture the surface forms, NP's from your corpora domain and then use the mentioned tool to tweak the model to your needs.

**Comment by benzitohhh** [comment]
@dav009 - thanks, that is really helpful - will check out the model editor.

Have a good weekend!
