### ISSUE TITLE
Questions regarding the API

### ISSUE THREAD

**Issue by shatu** [dbpedia-spotlight/dbpedia-spotlight#344]
Hi guys,

I am doing some study on named entity annotation systems, and would be really glad if you can answer the following questions :- 

1. Is it possible to get NIL mentions i.e. those named entity mentions (surface forms) which DBpedia couldn't link to its Knowledge-Base (either because of lack of sufficient confidence or because the target entity is out of its KB)? Note that, I'm asking this after setting all possible thresholds to zero. So, in other words - "Is there any difference in the number of mentions in the outputs of /spot and /annotate services (after setting all thresholds to zero)"? And if so, what do those missing mentions correspond to?

2. If I use the /candidates service, which attribute of the output corresponds to the score that is displayed alongside candidate entities on your demo webpage? Is it "finalScore"?

Thanks,
Shashank

**Comment by dav009** [comment]
Hi,

1. I'm a bit confused by the question. But: 
   - There are two steps:
     - Spotting: Finding the surface form in text, which is what the spot endpoint corresponds to
     - Disambiguating: Finding the right entity.
    So you could get some surface form's matched in the first step, which then are pruned in the disambiguation step because of a very high confidence parameter for example.

 - I'm not sure of what you mean with a `NIL` mention. My guess would be that all surface forms existing in the stores are attached to at least a topic.

2. The numbers displayed  correspond to `finalScore`. I'm assuming you are referring to the numbers you get when you call `n-best candidates` via the widget.

**Comment by shatu** [comment]
Hi, 

Firstly, many thanks for reverting back so quickly!

1. According to your definitions then, my question is :- 
    "If I set my confidence parameter to 0, will any surface form be pruned from the output of the spotting phase to the output of the disambiguation phase" i.e.
"Does each and every spot result into an annotation if I keep my confidence threshold to 0?" 

2. Yes, I was referring to those numbers only.

Thanks,
Shashank

**Comment by dav009** [comment]
So:
 I think in principle nothing will be pruned. But consider the following things happening:
 - the min value for confidence is 0.1 set up by default when you select somethign lower i.e : 0.0
 - Some Surface forms could be discarded i.e:
   consider you have to matches for the same anchor. i.e:   text : "New York" could generate two spot matches: (i) `New York` and (ii) `York` . Since they overlap on the tokens one of them will be selected.

**Comment by shatu** [comment]
Thanks, that should be all.
