### ISSUE TITLE
Building from source does not work using Scala 2.10 and Java 1.8

### ISSUE THREAD

**Issue by wouterbeek** [dbpedia-spotlight/dbpedia-spotlight#345]
I am trying to build DBpedia Spotlight (0b8152f484035e41229d7691415b19a9a7dc403a) from sources. This is my setup:
  - Fedora 21
  - OpenJDK 1.8.0_31
  - Scala 2.10.3

Upon running `mvn install` I get multiple errors of the following kind:

```
[WARNING]  Expected all dependencies to require Scala version: 2.9.2
[WARNING]  net.liftweb:lift-json_2.9.2:2.5-M1 requires scala version: 2.9.2
[WARNING]  net.liftweb:lift-json_2.9.2:2.5-M1 requires scala version: 2.9.2
[WARNING]  org.scala-lang:scalap:2.9.2 requires scala version: 2.9.2
[WARNING]  org.scalatest:scalatest_2.9.2:2.0.M4 requires scala version: 2.9.2
[WARNING]  org.scalaz:scalaz-core_2.9.2:6.0.4 requires scala version: 2.9.2
[WARNING]  org.scalanlp:breeze-math_2.9.2:0.1 requires scala version: 2.9.2
[WARNING]  org.scalanlp:breeze-process_2.9.2:0.1 requires scala version: 2.9.2
[WARNING]  org.scalanlp:breeze-learn_2.9.2:0.1 requires scala version: 2.9.2
[WARNING]  com.codecommit:anti-xml_2.9.1:0.3 requires scala version: 2.9.1
[WARNING] Multiple versions of scala libraries detected!
```

And later:

```
[ERROR] error: error while loading CharSequence, class file '/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.31-5.b13.fc21.x86_64/jre/lib/rt.jar(java/lang/CharSequence.class)' is broken
[INFO] (bad constant pool tag 18 at byte 10)
[ERROR] error: error while loading Arrays, class file '/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.31-5.b13.fc21.x86_64/jre/lib/rt.jar(java/util/Arrays.class)' is broken
[INFO] (bad constant pool tag 18 at byte 765)
[ERROR] error: error while loading AnnotatedElement, class file '/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.31-5.b13.fc21.x86_64/jre/lib/rt.jar(java/lang/reflect/AnnotatedElement.class)' is broken
[INFO] (bad constant pool tag 18 at byte 76)
...
```

Any ideas on how to solve this? It is not trivial to install Scala 2.9.2 *and* 2.9.1 on Fedora.

**Comment by jodaiber** [comment]
hey @wouterbeek, I think Scala shouldn't be the problem since it's packaged with the maven project. I suspect that it's Java 1.8. So Iwould try to run it with Java 1.7 or 1.6.

Jo

**Comment by dav009** [comment]
@wouterbeek as @jodaiber  mentioned scala version installed in your system shouldn't be the problem as it is automatically fetched by maven.

It is definitely java 8.I can confirm this since I have java 8 installed on my system and a few times I've forgotten to set java_home to 7 before compiling and it ended up burping in this way.

**Comment by wouterbeek** [comment]
Thanks @jodaiber and @dav009 for your quick response. Unfortunately I have not been able to roll back OpenJDK on Fedora yet. (It is actually quite difficult to do so!) Anyway... this is certainly not an issue in Spotlight, so I'm closing this topic now.
