### ISSUE TITLE
Debian Package Installation- 404 not found for en.tar.gz

### ISSUE THREAD

**Issue by sjuyal** [dbpedia-spotlight/dbpedia-spotlight#346]
Maybe the issue was raised earlier and closed but not yet rectified in the deb package.

I guess the issue is in postinst file dbpedia-spotlight-0.6.deb. It looks for http://spotlight.sztaki.hu/downloads/en.tar.gz for downloading the file which is not there. 

So the postinst file should be updated with 
DOWNLOAD_SITE="http://spotlight.sztaki.hu/downloads/version-0.1/

**Comment by dav009** [comment]
@sjuyal thanks.

I think most of this debian packaging is outdated/not working.

There is a mix of things here, first the current master branch points to spotlight 0.7.
I think in that regard the code generating this deb is outdated(the version as well , as it says it generated a spotlight `0.6` deb).
 So the master branch should try to download en_2+2.tar.gz in (http://spotlight.sztaki.hu/downloads/en_2+2.tar.gz )

If you are working on Spotlight 0.6 then your change is alright

It would be great to get this working properly again.

**Comment by sjuyal** [comment]
@dav009 thanks! Yes certainly the deb seems outdated. Maybe the mention of spotlight 0.6 in majority of the places in the documentation created the confusion.

**Comment by dav009** [comment]
If you could fix those references as you struggle to install spotlight it would be great.

Any luck getting it to run?

**Comment by sjuyal** [comment]
yes I got it working on my machine by doing some changes in postinst script in deb package. :)
But code generating this debian packaging certainly needs to be updated as others using the deb package might also be facing this issue.

**Comment by tgalery** [comment]
hi @sjuyal would you be able to fork the repo and submit a PR with the changes you introduced ?

**Comment by sjuyal** [comment]
@tgalery: As David has mentioned that current branch points to 0.7 so I guess only two changes are required for it to download en_2+2.tar.gz and make it run fine.
both changes are in "postinst" file :
 
DBPEDIA_SPOTLIGHT_VERSION=0.7
I18N_CODES=('da' 'de' 'en_2+2' 'es' 'fr' 'hu' 'it' 'pt' 'ru' 'sv' 'tr')
Somebody can review it first or should I fork and create a PR?

**Comment by jodaiber** [comment]
I can rename the en_2+2.gz model file to en.gz on the download page if that makes it easier.

**Comment by sjuyal** [comment]
@jodaiber But as I recall David mentioned in some issue that 2+2 has a significance wrt counts of surface form and context word. And there are other models present there too.
We can extend the Code list with all the models like:
I18N_CODES=('da' 'de' 'en_2+2' 'en_2+3' 'en_3+5' 'en_4+8' 'es' 'fr' 'hu' 'it' 'pt' 'ru' 'sv' 'tr'). And we can alter the script that if someone enters 'en' we can select en_2+2 by default

**Comment by jodaiber** [comment]
Yes, the lower the numbers, the less pruning there was performed on the model. We could certainly let al of them be specified but from a usability point of view, I think it would make more sense to have one default model (2+2), after all the i18n codes are supposed to be the languages, not model-specific parameters.
