### ISSUE TITLE
Accentuation

### ISSUE THREAD

**Issue by gpoveda** [dbpedia-spotlight/dbpedia-spotlight#349]
Hello,

Im trying to use the dbpedia-spotligth web service. However, currently Im facing a problem. When I try to use different accents, it  does not works, even when I was encoding the text. For example

By using the demo site with this word: Nízke Tatry it works!

By using the webservice not:

http://spotlight.dbpedia.org/rest/annotate?text=N%C3%ADzke+Tatry&confidence=0.5&support=0&spotter=CoOccurrenceBasedSelector&disambiguator=Default&policy=whitelist&types=&sparql=

Can you suggest me any solution for that?

thank you very much

**Comment by jodaiber** [comment]
Hey @gpoveda, the demo is not running the same endpoint that spotlight.dbpedia.org is running. spotlight.dbpedia.org is still an old endpoint (we should change that /cc @pablomendes). You can see the endpoint URL the demo is using at the bottom of the demo page.
