### ISSUE TITLE
Demo not working

### ISSUE THREAD

**Issue by owlmsj** [dbpedia-spotlight/dbpedia-spotlight#352]
Ports like 2225 and 2228 (french and portuguese) is not working.

**Comment by juaneduardo** [comment]
The same for spanish 2231

**Comment by dav009** [comment]
@owlmsj  @juaneduardo Sorry, It seems that the servers are usually bashed with requests, they are meant as demos for playing as opposed to stable services.
For those languages (Spanish, French and Portuguese) the models are small enough to fit in a 4G/8G machine, so most likely you could set them up locally if you want to play with them.
