### ISSUE TITLE
Dbpediaspotlight with other dataset

### ISSUE THREAD

**Issue by fatmaLyon** [dbpedia-spotlight/dbpedia-spotlight#358]
hi, i want to add onother dataset and especially from healthcare domain : Bio2RDF and others one in french.
is it possible to have some indication

thanks

**Comment by dav009** [comment]
I've used the [Model editor](https://github.com/idio/spotlight-model-editor) to tweak the vanilla model.

I guess with a few additions you could import your data using the model editor. that is:
- You have the topics, their possible surface forms, and some text associated with each topic.

**Comment by fatmaLyon** [comment]
thanks, 
i will try it
i hope it works,
