### ISSUE TITLE
Person names are likely to be mistaken for locations

### ISSUE THREAD

**Issue by nathanathan** [dbpedia-spotlight/dbpedia-spotlight#360]
In the spotlight demo, I've noticed that person names like Kent or Houston are likely to be mistaken for locations unless the full name of a notable person is used (e.g. [Houston Person](http://en.wikipedia.org/wiki/Houston_Person)). Does the current Spotlight statistical model have any mechanism by which names mistaken for locations could be ruled out when the people named are not notable?

**Comment by tgalery** [comment]
Hi Nathan, I think that the reason for this is that the statistics related to the surface form 'Houston' make the candidate Houston (the city) more likely than the person. Can you check whether the results are the same if the surrounding words (i.e. the context) contains many music related words ?

**Comment by nathanathan** [comment]
To clarify, I am concerned about the case where a person name that does not have a dbpedia entity associated with it is mistaken for a location. For example, in this sentence Houston is linked to the city when ideally nothing should be linked:
"Houston Fakelastname is not a notable person."
Houston Person is a notable name so it overrides the incorrect location name. In general, there is a mechanism for ruling out incorrect links based the availability of better links. I'm wondering if the statistical model is able to rule out incorrect links based on context and features like adjacent capitalization alone.
