### ISSUE TITLE
DBpedia Spotlight Demo takes long time

### ISSUE THREAD

**Issue by Hanan-Mahmoud** [dbpedia-spotlight/dbpedia-spotlight#362]
Hi Every one
I notice that DBpedia Spotlight takes long time to annotate the default text on the demo
does any one knows the reason of that?
I'm using DBpedia Spotlight on my code and I really want to find a solution for this
Regards

**Comment by SteelAlex** [comment]
Hi,

Did you use https protocol? If yes - annotation request just failed with 
```
Mixed Content: The page at 'https://dbpedia-spotlight.github.io/demo/' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://spotlight.sztaki.hu:2222/rest/annotate?text=First+documented+in+the+…rt=0&spotter=Default&disambiguator=Default&policy=whitelist&types=&sparql='. This request has been blocked; the content must be served over HTTPS.
``` 
and without response. If you use http (not https) then all works good.

**Comment by sandroacoelho** [comment]
Thanks @SteelAlex
