### ISSUE TITLE
Installing DBpedia Spotlight

### ISSUE THREAD

**Issue by Hanan-Mahmoud** [dbpedia-spotlight/dbpedia-spotlight#364]
Hello every one
I've installed DBpedia Spotlight 0.7 Jar file
and en.tar.gz for the statistical version as mentioned in this link:
https://github.com/dbpedia-spotlight/dbpedia-spotlight/wiki/Run-from-a-JAR
I'm using NetBeans IDE and I've added DBpedia Spotlight 0.7 jar file to my project library
but I have two questions:
1. where to put the en.tar.gz file after unzip it
2. in the previous link, what did they mean by this sentence:
java -jar dbpedia-spotlight.jar /data/spotlight/en/model_en http://localhost:2222/rest
where to type this command, on cmd or where?

**Comment by dav009** [comment]
Hi,

You are meant to run that command in the terminal (cmd)
You only need to download the model, uncompress it wherever you want, and
then run the given command.
So in other words you don't need to import the project to an IDE.

**Comment by Hanan-Mahmoud** [comment]
I did what you said but I got this in my cmd
-------------------------
C:\>java -jar dbpedia-spotlight.jar /data/spotlight/en/model_en http://localhost
:2222/rest
Exception in thread "main" java.io.IOException: Invalid Spotlight model folder:
Could not read required file tokens.mem in \data\spotlight\en\model_en\model\tok
ens.mem.
        at org.dbpedia.spotlight.db.SpotlightModel$$anonfun$storesFromFolder$1.a
pply(SpotlightModel.scala:45)
        at org.dbpedia.spotlight.db.SpotlightModel$$anonfun$storesFromFolder$1.a
pply(SpotlightModel.scala:43)
        at scala.collection.LinearSeqOptimized$class.foreach(LinearSeqOptimized.
scala:59)
        at scala.collection.immutable.List.foreach(List.scala:76)
        at org.dbpedia.spotlight.db.SpotlightModel$.storesFromFolder(SpotlightMo
del.scala:42)
        at org.dbpedia.spotlight.db.SpotlightModel$.fromFolder(SpotlightModel.sc
ala:62)
        at org.dbpedia.spotlight.db.SpotlightModel.fromFolder(SpotlightModel.sca
la)
        at org.dbpedia.spotlight.web.rest.Server.main(Server.java:126)

**Comment by sandroacoelho** [comment]
Hi @Hanan-Mahmoud ,

/data/spotlight/en/model_en is a valid path? Windows requires the drive into the path 

E.g: c:/data//spotlight/en/model_en.

Best,
