### ISSUE TITLE
DBpedia spotlight Demo stop working 

### ISSUE THREAD

**Issue by Hanan-Mahmoud** [dbpedia-spotlight/dbpedia-spotlight#365]
Hello,
I was using your webservice and it stopped working suddenly . even the Demo http://dbpedia-spotlight.github.com/demo/  doesn't annotate even the default text...

Could anyone tell me if this is a permanent stop to this service or just a temporary failure?

Thank you

**Comment by m1ci** [comment]
+1 same here! Can someone update on this?

**Comment by jodaiber** [comment]
Hey guys,

sorry, the services are running, but they seem to be abused by a few users, there are extreme numbers of requests. I restarted for now, but I am not sure what to do about this, do you have any ideas?

Jo

**Comment by phdowling** [comment]
Is it hard to add some rate limiting per IP address?

**Comment by jodaiber** [comment]
Probably not. I haven't done that before. PRs are welcome!

**Comment by m1ci** [comment]
Hi,
I've setup API rate limitting per api key for Entityclassifier.eu API . To implement it I used Redis - it provides all features for rate limitting: "increment" and "expire".
More on Redis and rate limitting here: http://redis.io/commands/INCR#pattern-rate-limiter
See my implementation
https://github.com/entityclassifier-eu/entityclassifier-core/tree/master/src/main/java/cz/vse/fis/keg/entityclassifier/core/redis
and 
https://github.com/entityclassifier-eu/entityclassifier-core/tree/master/src/main/java/cz/vse/fis/keg/entityclassifier/rest/authorizator

Feel free to reuse and modify the code according to your needs.

**Comment by Hanan-Mahmoud** [comment]
Thanks a lot..
you know.. my master thesis project was stopped and I almost give up
thanks again for your response

**Comment by dav009** [comment]
@Hanan-Mahmoud I think you should not rely on the demo.
 You could easily setup your own server, there is even a docker image for it https://registry.hub.docker.com/u/schot/dbpedia-spotlight/

**Comment by Hanan-Mahmoud** [comment]
is there any requirement for that?
I mean type of OS used, RAM to be used... or something like that?

**Comment by tgalery** [comment]
@jodaiber I think we could run the spotlight processes under supervisor http://supervisord.org/, so when the process stops, supervisord automatically restarts it (I think @dav009 sent a config a while ago). That said, some sort of limitation might be good to stop people abusing it. 
@Hanan-Mahmoud if you use the 0.7 version of the statistical model (current master) you would need to download the models for the languages you need (check the wiki) and for english it needs around 7-8G ram. Other languages require much less.

**Comment by nathanathan** [comment]
A Spotlight-as-a-service website might be successful. The english 2+2 model's 8GB memory footprint is pretty large. A VPS with enough ram it would cost at least 30$ a month. I think people like myself who want more reliability than the demo can provide but don't need to use spotlight that heavily would be willing to pay ~5$/month for a plan on a shared server. There are things that Spotlight does better than payed entity extraction services like Alchemy.

**Comment by jodaiber** [comment]
We have upgraded the demo server slightly (from 32GB to 49GB of RAM), that should increase reliability a bit, but rate limiting and supervisord would still be great (maybe @tgalery can have a look supervisord?).
