### ISSUE TITLE
Is there "language" parameter defined for the REST service?

### ISSUE THREAD

**Issue by m1ci** [dbpedia-spotlight/dbpedia-spotlight#366]
Hi there,

I was wondering whether there is implemented a "language" parameter which can be used to specify the language of the input text?

Thanks!

**Comment by dav009** [comment]
There is no language parameter via the rest endpoint.
The server takes a model when is being bootstraped, that model carries the language information.
If you want to play with the demo rest endpoints, there are different servers for each language.

**Comment by m1ci** [comment]
So, is every server for each language exposed via REST endpoint? If yes, can you provide list of those endpoints? BTW, it seems the English server is down. No results for English using the demo: http://dbpedia-spotlight.github.io/demo/

**Comment by dav009** [comment]
yes, the english demo server seems to be down.

endpoints:
http://dbpedia-spotlight.github.io/demo/config/sites.xml

**Comment by m1ci** [comment]
Oh, great! Thanks a lot for the pointer!
