### ISSUE TITLE
Outdated document

### ISSUE THREAD

**Issue by XuChen-Repair** [dbpedia-spotlight/dbpedia-spotlight#372]
Hello,

I tried to create a Spotlight model by following the instructions at https://github.com/dbpedia-spotlight/dbpedia-spotlight/wiki/Internationalization-%28DB-backed-core%29/5a19304332ed40f1b50e7de87f37b30633e558ff. However, this document seems outdated. For example, “nl-chunker.bin” is missing at http://opennlp.sourceforge.net/models-1.5/.
Could you please update this document?

**Comment by shubhamgoyal** [comment]
I am also facing the same issue

**Comment by dav009** [comment]
Hello Xu, Sorry for the late reply. 

Xu, given your email. I think you dont need to "Create " a new model. 
But rather use one of the available models. Below are the steps to setup a server that will give you the same annotations as the `demo` endpoint.

1. Download spotlight's jar: http://spotlight.sztaki.hu/downloads/dbpedia-spotlight-0.7.jar
2. Download spotlight's model: http://spotlight.sztaki.hu/downloads/en_2+2.tar.gz (this is the english one) . Other languages are available at:  http://spotlight.sztaki.hu/downloads/ ( fr, nl..etc)
3. uncompress the model. i.e:  `tar -xvf en_2+2.tar.gz`
4. run `java -Xmx10G -Xms10G -jar dbpedia-spotlight-0.7.jar
~/pathToModels/en/ http://localhost:2222/rest`
5. check http://localhost:2222/rest/anotate?text=Berlin&confidence=0.5

**Comment by dav009** [comment]
@shubhamgoyal do you need to build a model? or using the available one would suffice your needs?

**Comment by dav009** [comment]
@XuChen-Repair Also saw in your project that you are using spotlight `0.5` , I strongly recommend you to use 0.7.

**Comment by XuChen-Repair** [comment]
Hello, David,

Noted! Thank you so much!

Best Regards
Xu Chen

**Comment by XuChen-Repair** [comment]
Hello, David,

After following these instructions, I check  http://localhost:2222/rest/anotate?text=Berlin&confidence=0.5 <http://localhost:2222/rest/anotate?text=Berlin&confidence=0.5>.
However, the page is empty and in the terminal it states:

Server started in /Users/xuchen/Downloads/DBpediaSpotlight listening on http://localhost:2222/rest
Aug 26, 2015 7:12:18 PM com.sun.grizzly.http.servlet.ServletContextImpl log
INFO: null: init
Aug 26, 2015 7:12:18 PM com.sun.jersey.api.core.PackagesResourceConfig init
INFO: Scanning for root resource and provider classes in the packages:
  org.dbpedia.spotlight.web.rest.resources
Aug 26, 2015 7:12:21 PM com.sun.jersey.api.core.ScanningResourceConfig logClasses
INFO: Root resource classes found:
  class org.dbpedia.spotlight.web.rest.resources.Candidates
  class org.dbpedia.spotlight.web.rest.resources.Spot
  class org.dbpedia.spotlight.web.rest.resources.Disambiguate
  class org.dbpedia.spotlight.web.rest.resources.Feedback
  class org.dbpedia.spotlight.web.rest.resources.Annotate
Aug 26, 2015 7:12:21 PM com.sun.jersey.api.core.ScanningResourceConfig init
INFO: No provider classes found.
Aug 26, 2015 7:12:21 PM com.sun.jersey.server.impl.application.WebApplicationImpl _initiate
INFO: Initiating Jersey application, version 'Jersey: 1.10 11/02/2011 04:41 PM'
Aug 26, 2015 7:12:22 PM com.sun.jersey.api.wadl.config.WadlGeneratorLoader loadWadlGenerator
INFO: Loading wadlGenerator org.dbpedia.spotlight.web.rest.wadl.ExternalUriWadlGenerator

and it just get stuck at this line.

Do you have any suggestions?

Best Regards,
Xu Chen

**Comment by dav009** [comment]
mm can you paste the exact line you used on the terminal.

what OS is it running on?
what is the java version?

**Comment by XuChen-Repair** [comment]
INFO 2015-08-27 01:05:25,940 main [MemoryStore$] - Loading MemoryQuantizedCountStore...
 INFO 2015-08-27 01:05:26,047 main [MemoryStore$] - Done (105 ms)
 INFO 2015-08-27 01:05:26,047 main [MemoryStore$] - Loading MemoryTokenTypeStore...
 INFO 2015-08-27 01:05:26,334 main [MemoryTokenTypeStore] - Creating reverse-lookup for Tokens.
 INFO 2015-08-27 01:05:26,699 main [MemoryStore$] - Done (651 ms)
 INFO 2015-08-27 01:05:26,699 main [MemoryStore$] - Loading MemorySurfaceFormStore...
 INFO 2015-08-27 01:05:31,331 main [MemorySurfaceFormStore] - Summing total SF counts.
 INFO 2015-08-27 01:05:33,370 main [MemorySurfaceFormStore] - Creating reverse-lookup for surface forms, adding normalized surface forms.
 INFO 2015-08-27 01:05:42,341 main [MemoryStore$] - Done (15634 ms)
 INFO 2015-08-27 01:05:42,350 main [MemoryStore$] - Loading MemoryResourceStore...
 INFO 2015-08-27 01:05:46,581 main [MemoryResourceStore] - Creating reverse-lookup for DBpedia resources.
 INFO 2015-08-27 01:05:48,666 main [MemoryResourceStore] - Counting total support...
 INFO 2015-08-27 01:05:49,231 main [MemoryResourceStore] - Done.
 INFO 2015-08-27 01:05:49,233 main [MemoryStore$] - Done (6881 ms)
 INFO 2015-08-27 01:05:49,233 main [MemoryStore$] - Loading MemoryCandidateMapStore...
 INFO 2015-08-27 01:05:52,082 main [MemoryStore$] - Done (2848 ms)
 INFO 2015-08-27 01:05:52,084 main [MemoryStore$] - Loading MemoryContextStore...
 INFO 2015-08-27 01:07:04,503 main [MemoryStore$] - Done (72257 ms)
 INFO 2015-08-27 01:07:32,410 main [MemoryStore$] - Loading FSADictionary...
 INFO 2015-08-27 01:07:36,387 main [MemoryStore$] - Done (3975 ms)
 INFO 2015-08-27 01:07:38,617 main [Server] - Initiated 1 disambiguators.
 INFO 2015-08-27 01:07:38,618 main [Server] - Initiated 2 spotters.
Aug 27, 2015 1:07:39 AM com.sun.grizzly.Controller logVersion
INFO: GRIZZLY0001: Starting Grizzly Framework 1.9.48 - 8/27/15 1:07 AM
Server started in /Users/xuchen/Downloads/DBpediaSpotlight listening on http://localhost:2222/rest
Aug 27, 2015 1:07:51 AM com.sun.grizzly.http.servlet.ServletContextImpl log
INFO: null: init
Aug 27, 2015 1:07:51 AM com.sun.jersey.api.core.PackagesResourceConfig init
INFO: Scanning for root resource and provider classes in the packages:
  org.dbpedia.spotlight.web.rest.resources
Aug 27, 2015 1:07:54 AM com.sun.jersey.api.core.ScanningResourceConfig logClasses
INFO: Root resource classes found:
  class org.dbpedia.spotlight.web.rest.resources.Feedback
  class org.dbpedia.spotlight.web.rest.resources.Disambiguate
  class org.dbpedia.spotlight.web.rest.resources.Spot
  class org.dbpedia.spotlight.web.rest.resources.Annotate
  class org.dbpedia.spotlight.web.rest.resources.Candidates
Aug 27, 2015 1:07:54 AM com.sun.jersey.api.core.ScanningResourceConfig init
INFO: No provider classes found.
Aug 27, 2015 1:07:55 AM com.sun.jersey.server.impl.application.WebApplicationImpl _initiate
INFO: Initiating Jersey application, version 'Jersey: 1.10 11/02/2011 04:41 PM'
Aug 27, 2015 1:07:56 AM com.sun.jersey.api.wadl.config.WadlGeneratorLoader loadWadlGenerator
INFO: Loading wadlGenerator org.dbpedia.spotlight.web.rest.wadl.ExternalUriWadlGenerator


OS version: 10.10.5
java version: 1.7.0_79

**Comment by dav009** [comment]
my bad just saw I miss typed `annotate`:

could you please try again:
`http://localhost:2222/rest/annotate?text=Berlin&confidence=0.5`

**Comment by XuChen-Repair** [comment]
It works! If I need to query a text in a program, I should insert the query text in “http://localhost:2222/rest/annotate?text=querytext&confidence=0.5” format right? Then how I can retrieve the result as a list?

**Comment by dav009** [comment]
If your text is very long, do a `POST` request to the endpoint : `http://localhost:2222/rest/annotate` and your text in the field `text`, if you try to use a `GET` and your text is very long you will miss part of it.

You can get the result either as Json or as XML. You just need to pass the correct headers.
i.e getting json annotations In python:

```python
data= {
            "text": "Berlin...",
            "confidence": 0.1,
            "support": 10,
        }
headers = {'accept': 'application/json'}
result = requests.post("http://localhost:2222/rest/annotate", data=data,
                                 headers=headers, timeout=30)
print(result.text)
```

```json
{
    "@text": "Berlin...",
    "@confidence": "0.1",
    "@support": "10",
    "@types": "",
    "@sparql": "",
    "@policy": "whitelist",
    "Resources": [
        {
            "@URI": "http://dbpedia.org/resource/Berlin",
            "@support": "46739",
            "@types": "Schema:Place,DBpedia:Place,DBpedia:PopulatedPlace,DBpedia:Region,Schema:AdministrativeArea,DBpedia:AdministrativeRegion",
            "@surfaceForm": "Berlin",
            "@offset": "0",
            "@similarityScore": "0.997802614000239",
            "@percentageOfSecondRank": "0.0020366810433438726"
        }
    ]
}
```

**Comment by XuChen-Repair** [comment]
Dear David,

Thanks for helping, this code works. Right now, it takes 1~2 seconds to annotate a string text, is there a way to improve the speed?

Best Regards,
Xu Chen

**Comment by jodaiber** [comment]
Hey @XuChen-Repair,

if you allow it more memory usage, like `-xmX20g`, it should be faster.

Jo
