### ISSUE TITLE
Install and use DBpedia spotlight in Tomcat Server

### ISSUE THREAD

**Issue by lolitta747** [dbpedia-spotlight/dbpedia-spotlight#377]
Hi,
I am trying to install and use DBpedia spotlight in Tomcat but there are no references or back-support for doing that, and the Tomcat webpage is empty. Can you please give me some support in order to achieve that? Many thanks in advance.
Regards,

**Comment by dav009** [comment]
A few questions? have you run the vanilla server that comes by default? we have been using it on some production environments and it works quite well.

I've not used the war file. But if you do `mvn package`, a `.war` file will be generated in the target folder (`rest-tomcat/target`).

**Comment by lolitta747** [comment]
Thanks for your answer. Actually I need it to work on Tomcat. I got the war file and deployed it successfully in Tomcat, but I am still not able to configure it to work with my local data not with the online service. Do you have any idea how this could be achieved?

**Comment by sandroacoelho** [comment]
Hi @lolitta747 

Have you follow [these steps](https://github.com/dbpedia-spotlight/dbpedia-spotlight/wiki/Tomcat)?

Sorry to say that, but war files it will be discontinued.  

Best,
