### ISSUE TITLE
server.properties for dbpedia-spotlight-0.7.jar

### ISSUE THREAD

**Issue by mypolopony** [dbpedia-spotlight/dbpedia-spotlight#379]
Hi all,

Thanks for the great software! I have things working with `dbpedia-spotlight-0.7.jar` and `en_2+2`

My question is whether its possible to access / modify the settings. I'm happy with the current settings, but I want to see what they are, and tweak them just a bit.

I thought `java -Xmx12g -jar dbpedia-spotlight-0.7.jar /pbpedia/data/en_2+2 http://localhost:2222/rest/ -DaddArgs=/pbpedia/server.properties` might work, but I don't think so!

Thanks again!

**Comment by jodaiber** [comment]
Hi @mypolopony , there is no server.properties for the statistical backend as such. If you want to know more about the details, you can look at the paper and code. The only properties file is this:
http://spotlight.sztaki.hu/downloads/demo/en_2+2/model.properties

but it does not contain many parameters.

Jo
