### ISSUE TITLE
dbpedia-spotlight-ui debian pacakge

### ISSUE THREAD

**Issue by alegrm** [dbpedia-spotlight/dbpedia-spotlight#380]
Hello,

I'm maintainer of the LDStack http://stack.linkeddata.org/ which is the continuation of the Debian Repository of LD tools created in the LOD2 EU project.

I'm doing some cleanup and asking for the future of some outdated tools. A debian package called dbpedia-spotlight-ui is there:
http://stack.linkeddata.org/download/repo.php

I'd like to know if you are interested in maintaining this package in the repository (i.e. update the repository with recent versions), otherwise we will procede to remove it since there is no support.

Thanks in advance.
Alejandra.

**Comment by sandroacoelho** [comment]
Dear @alegrm ,

You can remove this package from the repository. This package contains only client-side stuffs (html, js, css) and it is out of date.

Would be awesome to have a complete Spotlight Debian package (with application and client side) hosted at LOD2, but we need to re-organize our release life cycle  first. When we have it done,  could you please tell us how can we request for hosting at LOD2 EU project?

Thank you for the patience and sorry for the big delay.
