### ISSUE TITLE
Server http://spotlight.dbpedia.org down?

### ISSUE THREAD

**Issue by psmuri** [dbpedia-spotlight/dbpedia-spotlight#386]
Hi, 

        I got an error when I call to the server? Is it down?

Caused by: org.apache.http.conn.ConnectTimeoutException: Connect to spotlight.dbpedia.org:80 [spotlight.dbpedia.org/134.155.95.15] failed: connect timed out 

Thanks in advance.

**Comment by psmuri** [comment]
Why did you close it?

**Comment by jodaiber** [comment]
Ah, sorry, I thought it was up again.

I recommend using the up-to-date statistical endpoint at http://spotlight.sztaki.hu:2222/rest

Jo

**Comment by psmuri** [comment]
Ok, Thank you very much. I tested it and works. You can close it now.

**Comment by jimkont** [comment]
recently some servers on Mannheim university failed that affected the DBpedia lookup service and the DBpedia mappings wiki.

Looks like spotlight.dbpedia.org was served from there, do you remember the behavior? (proxy, redirect, other) 
If you send me details I will contact the admins to re-set this up
```
$ host spotlight.dbpedia.org
spotlight.dbpedia.org has address 134.155.95.15
$ host 134.155.95.15
15.95.155.134.in-addr.arpa domain name pointer wifo5-02.informatik.uni-mannheim.de.
```

**Comment by psmuri** [comment]
Hi, sorry but I only have the url: spotlight.dbpedia.org . That is all I can provide you.

**Comment by jimkont** [comment]
Hi @psmuri this question was referring to @jodaiber / @pablomendes

**Comment by tgalery** [comment]
It might be a good idea to serve this under supiversor so it automatically re-starts the app if it crashes. In case it is gonna be setup again. A lot of issues we get are due to servers getting down.

**Comment by pablomendes** [comment]
It's not only about server restarts. My old implementation has systemic
issues when it's operating close to the max available memory. It
aggressively cached and crashed sometimes. This was the case with that
server, so we set it up to restart Spotlight periodically "until we fixed
the code". Talk about technical debt biting us back!

Besides putting it under upstart and potentially cron scheduling daily
restarts, we should take this opportunity and set up endpoints that better
describe the service.

I'd like to have explicit versions in the URLs. Perhaps:

http://spotlight.dbpedia.org/v0.6/ -> formerly
http://spotlight.dbpedia.org/rest (2011 paper)
http://spotlight.dbpedia.org/v0.7/ -> currently
http://spotlight.sztaki.hu:2222/rest/ (2013 paper)

But I don't want to route all of the traffic through U. Mannheim. Thoughts?

@jimkont can you put me in touch with whomever is managing the server now?
Anybody wants to help?

**Comment by ksuderman** [comment]
Are there any plans to restore the http://spotlight.dbpedia.org/ URLs?  Or at least redirect to  http://spotlight.sztaki.hu:2222/rest?
