### ISSUE TITLE
Enable LingPipeSpotter

### ISSUE THREAD

**Issue by aroris** [dbpedia-spotlight/dbpedia-spotlight#387]
http://spotlight.dbpedia.org/ seems to be down, so I downloaded the dbpedia-spotlight-0.7.jar and en_2+2.tar.gz from sztaki.hu and trying to use LingPipeSpotter getting the error below. _Need to know how to enable other spotters apart from the default._

**ERROR: Specified spotter=LingPipeSpotter has not been loaded. Use one of [SpotXmlParser, Default].**

Default works perfectly fine when I run the jar file using "java -jar dbpedia-spotlight-0.7.jar en_2+2 http://localhost:2222/rest"

The server log is attached. Running using JRE 1.8 on Windows 2012 Server. 

E:\LexiconGeneration\dbpedia>java -jar dbpedia-spotlight-0.7.jar en_2+2 http://localhost:2222/rest
 INFO 2015-12-16 02:14:09,434 main [MemoryStore$] - Loading MemoryQuantizedCountStore...
 INFO 2015-12-16 02:14:09,496 main [MemoryStore$] - Done (47 ms)
 INFO 2015-12-16 02:14:09,496 main [MemoryStore$] - Loading MemoryTokenTypeStore...
 INFO 2015-12-16 02:14:09,761 main [MemoryTokenTypeStore] - Creating reverse-lookup for Tokens.
 INFO 2015-12-16 02:14:10,307 main [MemoryStore$] - Done (811 ms)
 INFO 2015-12-16 02:14:10,307 main [MemoryStore$] - Loading MemorySurfaceFormStore...
 INFO 2015-12-16 02:14:20,666 main [MemorySurfaceFormStore] - Summing total SF counts.
 INFO 2015-12-16 02:14:22,194 main [MemorySurfaceFormStore] - Creating reverse-lookup for surface forms, adding normalized surface forms.
 INFO 2015-12-16 02:14:23,801 main [MemoryStore$] - Done (13494 ms)
 INFO 2015-12-16 02:14:23,817 main [MemoryStore$] - Loading MemoryResourceStore...
 INFO 2015-12-16 02:14:33,832 main [MemoryResourceStore] - Creating reverse-lookup for DBpedia resources.
 INFO 2015-12-16 02:14:35,501 main [MemoryResourceStore] - Counting total support...
 INFO 2015-12-16 02:14:36,484 main [MemoryResourceStore] - Done.
 INFO 2015-12-16 02:14:36,499 main [MemoryStore$] - Done (12682 ms)
 INFO 2015-12-16 02:14:36,499 main [MemoryStore$] - Loading MemoryCandidateMapStore...
 INFO 2015-12-16 02:14:39,073 main [MemoryStore$] - Done (2574 ms)
 INFO 2015-12-16 02:14:39,073 main [MemoryStore$] - Loading MemoryContextStore...
 INFO 2015-12-16 02:15:11,474 main [MemoryStore$] - Done (32401 ms)
 INFO 2015-12-16 02:15:15,062 main [MemoryStore$] - Loading FSADictionary...
 INFO 2015-12-16 02:15:15,577 main [MemoryStore$] - Done (499 ms)
 INFO 2015-12-16 02:15:15,842 main [Server] - Initiated 1 disambiguators.
 INFO 2015-12-16 02:15:15,842 main [Server] - Initiated 2 spotters.
Dec 16, 2015 2:15:16 AM com.sun.grizzly.Controller logVersion
INFO: GRIZZLY0001: Starting Grizzly Framework 1.9.48 - 12/16/15 2:15 AM
Server started in E:\LexiconGeneration\dbpedia listening on http://localhost:2222/rest
Dec 16, 2015 2:16:01 AM com.sun.grizzly.http.servlet.ServletContextImpl log
INFO: null: init
Dec 16, 2015 2:16:01 AM com.sun.jersey.api.core.PackagesResourceConfig init
INFO: Scanning for root resource and provider classes in the packages:
  org.dbpedia.spotlight.web.rest.resources
Dec 16, 2015 2:16:04 AM com.sun.jersey.api.core.ScanningResourceConfig logClasses
INFO: Root resource classes found:
  class org.dbpedia.spotlight.web.rest.resources.Candidates
  class org.dbpedia.spotlight.web.rest.resources.Spot
  class org.dbpedia.spotlight.web.rest.resources.Feedback
  class org.dbpedia.spotlight.web.rest.resources.Annotate
  class org.dbpedia.spotlight.web.rest.resources.Disambiguate
Dec 16, 2015 2:16:04 AM com.sun.jersey.api.core.ScanningResourceConfig init
INFO: No provider classes found.
Dec 16, 2015 2:16:04 AM com.sun.jersey.server.impl.application.WebApplicationImpl _initiate
INFO: Initiating Jersey application, version 'Jersey: 1.10 11/02/2011 04:41 PM'
Dec 16, 2015 2:16:05 AM com.sun.jersey.api.wadl.config.WadlGeneratorLoader loadWadlGenerator
INFO: Loading wadlGenerator org.dbpedia.spotlight.web.rest.wadl.ExternalUriWadlGenerator
 INFO 2015-12-16 02:16:15,029 Grizzly-2222(3) [SpotlightInterface] - ******************************** Parameters ********************************
 INFO 2015-12-16 02:16:15,029 Grizzly-2222(3) [SpotlightInterface] - API: /annotate
 INFO 2015-12-16 02:16:15,029 Grizzly-2222(3) [SpotlightInterface] - client ip: 0:0:0:0:0:0:0:1
 INFO 2015-12-16 02:16:15,029 Grizzly-2222(3) [SpotlightInterface] - text: Use previous knowledge of surface area to make connections to the formulas for lateral and total surface area and determine
olutions for problems involving rectangular prisms, triangular prisms, and cylinders
 INFO 2015-12-16 02:16:15,029 Grizzly-2222(3) [SpotlightInterface] - text length in chars: 209
 INFO 2015-12-16 02:16:15,029 Grizzly-2222(3) [SpotlightInterface] - confidence: 0.0
 INFO 2015-12-16 02:16:15,029 Grizzly-2222(3) [SpotlightInterface] - support: 0
 INFO 2015-12-16 02:16:15,029 Grizzly-2222(3) [SpotlightInterface] - types:
 INFO 2015-12-16 02:16:15,029 Grizzly-2222(3) [SpotlightInterface] - sparqlQuery:
 INFO 2015-12-16 02:16:15,029 Grizzly-2222(3) [SpotlightInterface] - policy: false
 INFO 2015-12-16 02:16:15,029 Grizzly-2222(3) [SpotlightInterface] - coreferenceResolution: true
 INFO 2015-12-16 02:16:15,029 Grizzly-2222(3) [SpotlightInterface] - spotter: Default
 INFO 2015-12-16 02:16:15,029 Grizzly-2222(3) [SpotlightInterface] - disambiguator: Default
-- org.jblas ERROR Couldn't load copied link file: java.lang.UnsatisfiedLinkError: C:\Users\user1\AppData\Local\Temp\3\jblas1264030286519875694jblas.dll: Can't find dependent libraries.

 INFO 2015-12-16 02:16:16,214 Grizzly-2222(3) [TypeFilter] - types are empty: showing all types
 INFO 2015-12-16 02:16:16,230 Grizzly-2222(3) [SpotlightInterface] - HTML format
 INFO 2015-12-16 02:17:31,889 Grizzly-2222(2) [SpotlightInterface] - ******************************** Parameters ********************************
 INFO 2015-12-16 02:17:31,889 Grizzly-2222(2) [SpotlightInterface] - API: /annotate
 INFO 2015-12-16 02:17:31,889 Grizzly-2222(2) [SpotlightInterface] - client ip: 0:0:0:0:0:0:0:1
 INFO 2015-12-16 02:17:31,889 Grizzly-2222(2) [SpotlightInterface] - text: Use previous knowledge of surface area to make connections to the formulas for lateral and total surface area and determine
olutions for problems involving rectangular prisms, triangular prisms, and cylinders
 INFO 2015-12-16 02:17:31,889 Grizzly-2222(2) [SpotlightInterface] - text length in chars: 209
 INFO 2015-12-16 02:17:31,889 Grizzly-2222(2) [SpotlightInterface] - confidence: 0.0
 INFO 2015-12-16 02:17:31,889 Grizzly-2222(2) [SpotlightInterface] - support: 0
 INFO 2015-12-16 02:17:31,889 Grizzly-2222(2) [SpotlightInterface] - types:
 INFO 2015-12-16 02:17:31,889 Grizzly-2222(2) [SpotlightInterface] - sparqlQuery:
 INFO 2015-12-16 02:17:31,905 Grizzly-2222(2) [SpotlightInterface] - policy: false
 INFO 2015-12-16 02:17:31,905 Grizzly-2222(2) [SpotlightInterface] - coreferenceResolution: true
 INFO 2015-12-16 02:17:31,905 Grizzly-2222(2) [SpotlightInterface] - spotter: LingPipeSpotter
 INFO 2015-12-16 02:17:31,905 Grizzly-2222(2) [SpotlightInterface] - disambiguator: Default
 INFO 2015-12-16 02:17:31,920 Grizzly-2222(2) [SpotlightInterface] - ERROR: Specified spotter=LingPipeSpotter has not been loaded. Use one of [SpotXmlParser, Default].
 INFO 2015-12-16 02:17:31,920 Grizzly-2222(2) [SpotlightInterface] - HTML format

**Comment by jodaiber** [comment]
Hi,

the spotlight.dbpedia.org endpoint was running the Lucene-backed Spotlight. The current Spotlight, which is the one you downloaded, does not support the LingPipe Spotter.

Best,
Jo

**Comment by aroris** [comment]
Thanks for the response. Is there some way I can download the Lucene version?  The download links mentioned in the wiki at dbpedia.org are not working anymore.
