### ISSUE TITLE
Annotate REST end point is down.

### ISSUE THREAD

**Issue by srijiths** [dbpedia-spotlight/dbpedia-spotlight#388]
Is this http://spotlight.dbpedia.org/rest/annotate down ?

**Comment by jodaiber** [comment]
Hi @srijiths,

I recommend using the up-to-date endpoint at http://spotlight.sztaki.hu:2222/rest

spotlight.dbpedia.org/rest was the old Lucene-backed Spotlight. Please see the citation hints [here](https://github.com/dbpedia-spotlight/dbpedia-spotlight#citation) if you use it in academic work.

Best,
Jo

**Comment by srijiths** [comment]
Hi jodaiber,

Thanks for sharing this. I tried this. Is it possible to get a JSON response from this URL. Previously i was using Apache Stanbol with Spotlight REST end point and it does the response parsing of Entity type and Entity values.

Now here when i use http://spotlight.sztaki.hu:2222/rest/annotate , i am getting a plain result with reference to DBPedia topics. If this is the case how can i get the Entity mentions and its type from this.

Thank You

**Comment by dav009** [comment]
You can pass the header "Accept: application/json" to get json out of it.
The types are returned within the vanilla response

**Comment by srijiths** [comment]
Thanks dav009, It works.
