### ISSUE TITLE
Cannot download the required data files

### ISSUE THREAD

**Issue by vihari** [dbpedia-spotlight/dbpedia-spotlight#389]
Looks like http://spotlight.dbpedia.org/download/ is down, can someone take a look at this.
Thanks

**Comment by afader** [comment]
+1 :smile:

**Comment by afader** [comment]
@vihari FYI, I looked on web.archive.org and found that your link at one time redirected to http://wifo5-04.informatik.uni-mannheim.de/downloads/ which is online.

**Comment by vihari** [comment]
@afader Good thinking. Thanks!

**Comment by jodaiber** [comment]
Hi,

the old download page contained only the now deprecated Lucene backend. The downloads for the current version are here:

http://spotlight.sztaki.hu/downloads/

Best,
Jo

**Comment by afader** [comment]
Thanks, @jodaiber. Are the lexicalizations still available somewhere? I couldn't find them in your link.

**Comment by jodaiber** [comment]
Hey @afader,

we don't produce them as a file (we can if there is interest). But, if I recall correctly what they are, then they are basically the two first columns in the pairCounts files. For example, for Dutch:
http://spotlight.sztaki.hu/downloads/raw/nl/pairCounts

You can download those for any language here:

http://spotlight.sztaki.hu/downloads/raw/

Jo

**Comment by afader** [comment]
@jodaiber Cool, that should work for me. Thanks a ton!
