### ISSUE TITLE
Non-deterministic ranking in /candidates?

### ISSUE THREAD

**Issue by pablomendes** [dbpedia-spotlight/dbpedia-spotlight#39]
Converted from [SourceForge issue 3426030](http://sourceforge.net/support/tracker.php?aid=3426030), submitted by pablomendes

"I want to display only the first 3 resources in each surfaceform, and present up to 5 surface form in each turn. However, Spotlight seems to be mysterious to me, as it always gives different results... My question is: are the resource candidates in the surfaceform ordered by relevance? Can I limit the search so that I can get the top 3 or 5 only?"

**Comment by sandroacoelho** [comment]
This issue is not valid anymore. We will replace Lucene in a new version.
