### ISSUE TITLE
Rest Web Service

### ISSUE THREAD

**Issue by hodaraad** [dbpedia-spotlight/dbpedia-spotlight#393]
I'm wondering what has happened to the Dbpedia Spotlight web service at this address: 

http://spotlight.dbpedia.org/rest/annotate

It used to work a couple of months ago that I used it, but now nothing is shown. Tracking the http request message, it says "permanently moved".

Will there not be a Rest service available any more?

Also, I installed a local version, and it does not seem to return the same results I used to get with the web service. For instance, for this sentence "He is a politician, and songwriter", I would get both Politician and songwriter tagged while seeing their types (in the output of the json response object) mentioned to be for instance "Freebase/profession", "Freebase/occupation", etc. But, the local version just returns these two concepts, but the types parts are empty like this:

{u'@support': u'7570', u'@URI': u'http://dbpedia.org/resource/Songwriter', u'@surfaceForm': u'songwriter', u'@offset': u'85', u'@percentageOfSecondRank': u'0.003276048833808201', u'@similarityScore': u'0.9966708280647963', u'@types': u''}

I tested the demo service, and got the same results as my local version. But, I'm sure I would got a different results with the web service.

What am I missing here?

Thanks,

**Comment by sandroacoelho** [comment]
Hi @hodaraad ,

The current web service is hosted at spotlight.sztaki.hu for the follow languages

* English - http://spotlight.sztaki.hu:2222/rest/annotate
* German  - http://spotlight.sztaki.hu:2226/rest/annotate
* Dutch  -  http://spotlight.sztaki.hu:2232/rest/annotate
* French -  http://spotlight.sztaki.hu:2225/rest/annotate
* Italian - http://spotlight.sztaki.hu:2230/rest/annotate
* Russian - http://spotlight.sztaki.hu:2227/rest/annotate
* Spanish -  http://spotlight.sztaki.hu:2231/rest/annotate
* Portuguese - http://spotlight.sztaki.hu:2228/rest/annotate
* Hungarian - http://spotlight.sztaki.hu:2229/rest/annotate
* and Turkish - http://spotlight.sztaki.hu:2235/rest/annotate

And the web app is at http://dbpedia-spotlight.github.io/demo/

The service under http://spotlight.dbpedia.org/rest/annotate is not available anymore (Lucene version). 

I am trying to recovery that service with an old files that I found here. With some lucky, we will have v0.5 and v0.6 under [docker](http://hub.docker.com/u/dbpedia). 

Please, stay tunned on our DBpediaSpotlight Users List <dbp-spotlight-users@lists.sourceforge.net>

Best,

**Comment by jodaiber** [comment]
The new models do not have types yet. This is a bug and the models will be updated in a few days.

Jo

**Comment by hodaraad** [comment]
Any update on types support in new models? The web service seems to not support these yet.

**Comment by jodaiber** [comment]
Hey @hodaraad, we haven't switched the web service to the new models yet. That needs some more testing first. However, the models are now up-to-date and contain types.

**Comment by hodaraad** [comment]
I just tried installing a new copy of dbpedia spotlight based on the available docker image, and it seems types have not been updated. I still do not get types for some annotations such as "producer", "singer", "Liberal Party of Canada", "December 25th", etc.

is this the version that you were referring to as the up-to-date one? if so, does it mean that some mentions do not have any types assigned to? which ones have, which ones, don't?

Thanks,

**Comment by jodaiber** [comment]
Hi @hodaraad,

only DBpedia/Schema and Wikidata types that are part of the DBpedia extraction are provided. The examples you mention do not have any of these types in DBpedia, e.g. http://dbpedia.org/page/Singing, http://dbpedia.org/page/December_25. The up-to-date models are here [1]. They should be used in the latest docker.

Jo
[1] http://spotlight.sztaki.hu/downloads/latest_models/

**Comment by sandroacoelho** [comment]
Hi @hodaraad , @jodaiber 

On Docker, the last build was before yesterday as you can see [here](https://hub.docker.com/r/dbpedia/spotlight-english/builds/)

**Comment by hodaraad** [comment]
Thank you for your response. Can you be more clear about what are the types included in the DBpedia extraction? Where can I fined them?

Also, is it possible to provide a custom dictionary of terms for annotation? For instance, I wanted to annotate a text using a company-owned list of terms.

Another alternative for me is  to use the sparql query parameter in the Rest API. But, I could not get it work. For instance, I tried the following request (using bottle request package) to annotate only countries, and it fails giving a 400 error.

_payload = {'text': 'Justin Barack called all of these countries as enemies: Iran, United States, Japan, and Canada','confidence':'0.2','support':'30'} , 'sparql':'SELECT DISTINCT ?name  WHERE { ?country a dbo:Country . ?country rdfs:label ?name. FILTER (langMatches(lang(?name), "en"))'}_

how exactly the sparql parameter needs to be given?

**Comment by jodaiber** [comment]
Hi @hodaraad,

there's more about the types here: 

http://wiki.dbpedia.org/services-resources/datasets/data-set-39

and if you want to see all of them, you can look at this file:

http://downloads.dbpedia.org/3.9/en/instance_types_en.nt.bz2

(those are not fully up to date, I think, but should give the idea). You can also check the DBpedia documentation on http://wiki.dbpedia.org/.

I think the SPARQL filter is not active on the public endpoint, but if you want to filter by type you can do that via the following request (`&policy=whitelist&types=DBpedia%3APlace`):

`http://spotlight.sztaki.hu:2222/rest/annotate?text=First+documented+in+the+13th+century%2C+Berlin+was+the+capital+of+the+Kingdom+of+Prussia+(1701%E2%80%931918)%2C+the+German+Empire+(1871%E2%80%931918)%2C+the+Weimar+Republic+(1919%E2%80%9333)+and+the+Third+Reich+(1933%E2%80%9345).+Berlin+in+the+1920s+was+the+third+largest+municipality+in+the+world.+After+World+War+II%2C+the+city+became+divided+into+East+Berlin+--+the+capital+of+East+Germany+--+and+West+Berlin%2C+a+West+German+exclave+surrounded+by+the+Berlin+Wall+from+1961%E2%80%9389.+Following+German+reunification+in+1990%2C+the+city+regained+its+status+as+the+capital+of+Germany%2C+hosting+147+foreign+embassies.&confidence=0.5&support=0&spotter=Default&disambiguator=Default&policy=whitelist&types=DBpedia%3APlace&sparql=`

**Comment by AELBRK** [comment]
hi 
i build the English models using the run.sh scrip in Quick Starter
https://github.com/dbpedia-spotlight/model-quickstarter,
the model works fine but i don't get the types, it looks like the types are not part of the new model.

the following sample work on the pre-build downloaded model 

curl http://localhost:2222/rest/annotate --data "confidence=0.2" --data "support=20"  -H "Accept: application/json"  --data-urlencode "text=President Obama called Wednesday on Congress to extend a tax break for students included in last year's economic stimulus package, arguing that the policy provides more generous assistance." --data "types=Person,Organisation"

but on the new build model getting the following response:

"@text": "President Obama called Wednesday on Congress to extend a tax break for students included in last year's economic stimulus package, arguing that the policy provides more generous assistance.",
  "@confidence": "0.2",
  "@support": "20",
  "@types": "Person,Organisation",
  "@sparql": "",
  "@policy": "whitelist"


and the server log show:
ubuntu@ip-10-153-131-172:~/mount/dbpedia$ 4766549 [Grizzly-2222(1)] INFO org.dbpedia.spotlight.web.rest.SpotlightInterface - ******************************** Parameters ********************************
4766549 [Grizzly-2222(1)] INFO org.dbpedia.spotlight.web.rest.SpotlightInterface - API: /annotate
4766549 [Grizzly-2222(1)] INFO org.dbpedia.spotlight.web.rest.SpotlightInterface - client ip: 127.0.0.1
4766549 [Grizzly-2222(1)] INFO org.dbpedia.spotlight.web.rest.SpotlightInterface - text: President Obama called Wednesday on Congress to extend a tax break for students included in last year's economic stimulus package, arguing that the policy provides more generous assistance.
4766549 [Grizzly-2222(1)] INFO org.dbpedia.spotlight.web.rest.SpotlightInterface - text length in chars: 189
4766549 [Grizzly-2222(1)] INFO org.dbpedia.spotlight.web.rest.SpotlightInterface - confidence: 0.2
4766549 [Grizzly-2222(1)] INFO org.dbpedia.spotlight.web.rest.SpotlightInterface - support: 20
4766549 [Grizzly-2222(1)] INFO org.dbpedia.spotlight.web.rest.SpotlightInterface - types: Person,Organisation
4766549 [Grizzly-2222(1)] INFO org.dbpedia.spotlight.web.rest.SpotlightInterface - sparqlQuery:
4766549 [Grizzly-2222(1)] INFO org.dbpedia.spotlight.web.rest.SpotlightInterface - policy: false
4766549 [Grizzly-2222(1)] INFO org.dbpedia.spotlight.web.rest.SpotlightInterface - coreferenceResolution: true
4766549 [Grizzly-2222(1)] INFO org.dbpedia.spotlight.web.rest.SpotlightInterface - spotter: Default
4766549 [Grizzly-2222(1)] INFO org.dbpedia.spotlight.web.rest.SpotlightInterface - disambiguator: Default
4766574 [Grizzly-2222(1)] INFO org.dbpedia.spotlight.filter.annotations.TypeFilter - filtered out by type Whitelist: DBpediaResource[Barack_Obama] list=List(DBpedia:Person,DBpedia:Organisation)
4766575 [Grizzly-2222(1)] INFO org.dbpedia.spotlight.filter.annotations.TypeFilter - filtered out by type Whitelist: DBpediaResource[Religious_calling] list=List(DBpedia:Person,DBpedia:Organisation)
4766575 [Grizzly-2222(1)] INFO org.dbpedia.spotlight.filter.annotations.TypeFilter - filtered out by type Whitelist: DBpediaResource[Wednesday] list=List(DBpedia:Person,DBpedia:Organisation)
4766575 [Grizzly-2222(1)] INFO org.dbpedia.spotlight.filter.annotations.TypeFilter - filtered out by type Whitelist: DBpediaResource[United_States_Congress] list=List(DBpedia:Person,DBpedia:Organisation)
4766575 [Grizzly-2222(1)] INFO org.dbpedia.spotlight.filter.annotations.TypeFilter - filtered out by type Whitelist: DBpediaResource[Tax_break] list=List(DBpedia:Person,DBpedia:Organisation)
4766575 [Grizzly-2222(1)] INFO org.dbpedia.spotlight.filter.annotations.TypeFilter - filtered out by type Whitelist: DBpediaResource[Student] list=List(DBpedia:Person,DBpedia:Organisation)
4766575 [Grizzly-2222(1)] INFO org.dbpedia.spotlight.filter.annotations.TypeFilter - filtered out by type Whitelist: DBpediaResource[American_Recovery_and_Reinvestment_Act_of_2009] list=List(DBpedia:Person,DBpedia:Organisation)
4766575 [Grizzly-2222(1)] INFO org.dbpedia.spotlight.filter.annotations.TypeFilter - filtered out by type Whitelist: DBpediaResource[Argument] list=List(DBpedia:Person,DBpedia:Organisation)
4766575 [Grizzly-2222(1)] INFO org.dbpedia.spotlight.filter.annotations.TypeFilter - filtered out by type Whitelist: DBpediaResource[Policy] list=List(DBpedia:Person,DBpedia:Organisation)
4766575 [Grizzly-2222(1)] INFO org.dbpedia.spotlight.filter.annotations.TypeFilter - filtered out by type Whitelist: DBpediaResource[Generosity] list=List(DBpedia:Person,DBpedia:Organisation)
4766575 [Grizzly-2222(1)] INFO org.dbpedia.spotlight.filter.annotations.TypeFilter - filtered out by type Whitelist: DBpediaResource[Welfare] list=List(DBpedia:Person,DBpedia:Organisation)
4766576 [Grizzly-2222(1)] INFO org.dbpedia.spotlight.web.rest.SpotlightInterface - XML format
4766577 [Grizzly-2222(1)] INFO net.sf.json.xml.XMLSerializer - Using default type string
4766577 [Grizzly-2222(1)] INFO org.dbpedia.spotlight.web.rest.SpotlightInterface - JSON format

please let me know if i need to pass any parameter to the run.sh before building the model

**Comment by sandroacoelho** [comment]
Hi @AELBRK ,

Could you please open this issue [here](https://github.com/dbpedia-spotlight/model-quickstarter)?

Thanks,
