### ISSUE TITLE
memory problem with running local version of the latest jar file

### ISSUE THREAD

**Issue by hodaraad** [dbpedia-spotlight/dbpedia-spotlight#396]
I downloaded and extracted the newest jar file, and trying to run my local server like the following:

java -Xmx2g -jar dbpedia-spotlight-latest.jar en http://localhost:2222/rest

(I tried different memory size)

but after for a long time at the following step:

Loading MemoryResourceStore

it gives me the following error:

Exception in thread "main" java.lang.OutOfMemoryError: GC overhead limit exceeded

Thanks,
--Hoda

**Comment by tgalery** [comment]
You should assign at least 7g of xmx, have you tried that?

**Comment by hodaraad** [comment]
It gave me this error:

Cannot allocate memory' (errno=12)

Does it mean my system cannot allocate this much memory? What have changed in the latest version that it requires so much memory? the docker version installation ran successfully so fast, but I'm looking for an update mentioned applied in this version.

**Comment by tgalery** [comment]
Ermmm probably how much available ram you got?

**Comment by hodaraad** [comment]
I think 7G.

KiB Mem:   7552868 total,  2116412 used,  5436456 free,    13996 buffers

But, again why the docker and older versions could be installed easily? Can't anything be done for it?

**Comment by dav009** [comment]
English docker heap values are hard coded to -Xms12G -Xmx16G  
https://github.com/dbpedia-spotlight/spotlight-docker/blob/master/v0.7/english/spotlight.sh

try running your script with -Xmx6G -Xms6G Im not sure it will run, but worth giving it a try

**Comment by sandroacoelho** [comment]
Hi @hodaraad,

Docker is using the same version available available for download.

For english model, we are using -Xms12g -Xms16g.
