### ISSUE TITLE
Make web service available to computers on the same LAN

### ISSUE THREAD

**Issue by timov** [dbpedia-spotlight/dbpedia-spotlight#401]
Is it possible that instead of http://localhost:2222/rest I make the web service available on the local network so all the machines connected to that network can make requests to the web service?

**Comment by sandroacoelho** [comment]
Hi @timov,
Sure. Just replace localhost for your local IP. You can type ifconfig (on linux terminal) or ipconfig(on windows command) to discovery it.

E.g:

ifconfig [...]
eth0      Link encap:Ethernet  Endereço de HW 78:2b:cb:bf:ed:34  
          inet end.: *10.3.2.98*  Bcast:10.3.255.255  Masc:255.255.0.0
          endereço inet6: fe80::7a2b:cbff:febf:ed34/64 Escopo:Link
          UP BROADCASTRUNNING MULTICAST  MTU:1500  Métrica:1
          RX packets:1560462 errors:0 dropped:0 overruns:0 frame:0
          TX packets:874729 errors:0 dropped:0 overruns:0 carrier:0
          colisões:0 txqueuelen:1000 
          RX bytes:535161499 (510.3 MiB)  TX bytes:181791691 (173.3 MiB)
          IRQ:20 Memória:f7c00000-f7c20000 

My local ip is 10.3.2.98, so my spotlight address will be http://10.3.2.98:2222/rest
