### ISSUE TITLE
Rel8: where is index-0.6-withTypes-withSF?

### ISSUE THREAD

**Issue by ppedemon** [dbpedia-spotlight/dbpedia-spotlight#403]
Hi. I've downloaded the latest version of dbpedia-spotlight. Everything is working swiftly, but when trying to run rel8 (`java -cp dbpedia-spotlight-latest.jar org.dbpedia.spotlight.web.rest.RelatedResources`) I get this error:

```
Exception in thread "main" org.apache.lucene.store.NoSuchDirectoryException: directory '/data/spotlight/release-0.6/index-0.6-withTypes-withSF' does not exist
```

Upon inspection of  `RelatedResourced.scala`, on init the class attempts to load a Lucene index from the folder mentioned in the Exception message. I'm ok with the hard-coded location, but that index belongs to release-0.6, and it seems to be no longer available (the links to download the index are broken).

Am I trying to startup the Rel8 service correctly? If so, where can I get the missing index file?

**Comment by pablomendes** [comment]
Rel8 was never properly cleaned up for a release, thus the hardcode. The index is built through the so called "Lucene backend" index module. If you get around to making it read arguments from command line and testing with the latest Lucene indexes, please send a pull request. @sandroacoelho or myself can merge it in.

**Comment by sandroacoelho** [comment]
Hi @pablomendes , @ppedemon 

The latest model and the model builder for DBpedia Spotlight Lucene is available [here](https://github.com/dbpedia-spotlight/lucene-quickstarter). 

I will close this issue. If you need/want something more, you can open a new issue.

Best,
