### ISSUE TITLE
Latest installation guide that is outdated

### ISSUE THREAD

**Issue by YJ14** [dbpedia-spotlight/dbpedia-spotlight#408]
Hello everyone,
I am trying to maven install depedia-spotlight on mac os x according to the guide on github, but I am facing many inconsistencies in the documentations. These include outdated links, overlapped versions, build failures in every stage. 

Is there actually any recent installation guide that could help?

Best,

**Comment by sandroacoelho** [comment]
Hi @Palbear,

I advise you use Spotlight in docker (https://github.com/dbpedia-spotlight/spotlight-docker).

We are planning to do big refactoring in Spotlight soon to organize the repo.

**Comment by Palbear** [comment]
Hi @sandroacoelho 
Thanks for your comment. I will test the docker asap and write back my feedback.

**Comment by Palbear** [comment]
Hi @sandroacoelho 
I downloaded the docker repo and tried the first comman for the german docker file: 

`docker build -f Dockerfile  -t german_spotlight .`

Unfortunately I get this error:

```
Sending build context to Docker daemon 4.608 kB
Step 1 : FROM debian:squeeze
 ---> a873733ef581
Step 2 : MAINTAINER DBpedia Spotlight Team <dbp-spotlight-developers@lists.sourceforge.net>
 ---> Using cache
 ---> c274d92ef020
Step 3 : RUN apt-get update && apt-get install -y     curl     openjdk-6-jre
 ---> Running in 1427d8219837
Ign http://httpredir.debian.org squeeze Release.gpg
Ign http://httpredir.debian.org squeeze-updates Release.gpg
Ign http://httpredir.debian.org squeeze-lts Release.gpg
Ign http://httpredir.debian.org squeeze Release
Get:1 http://security.debian.org squeeze/updates Release.gpg [836 B]
Get:2 http://security.debian.org squeeze/updates Release [86.9 kB]
Ign http://httpredir.debian.org squeeze-updates Release
Ign http://httpredir.debian.org squeeze-lts Release
Get:3 http://security.debian.org squeeze/updates/main amd64 Packages [455 kB]
Err http://httpredir.debian.org squeeze/main amd64 Packages
  404  Not Found [IP: 128.31.0.66 80]
Err http://httpredir.debian.org squeeze-updates/main amd64 Packages
  404  Not Found [IP: 5.153.231.35 80]
Err http://httpredir.debian.org squeeze-lts/main amd64 Packages
  404  Not Found [IP: 198.145.20.143 80]
W: Failed to fetch http://httpredir.debian.org/debian/dists/squeeze/main/binary-amd64/Packages.gz  404  Not Found [IP: 128.31.0.66 80]

Fetched 543 kB in 13s (39.3 kB/s)
W: Failed to fetch http://httpredir.debian.org/debian/dists/squeeze-updates/main/binary-amd64/Packages.gz  404  Not Found [IP: 5.153.231.35 80]

W: Failed to fetch http://httpredir.debian.org/debian/dists/squeeze-lts/main/binary-amd64/Packages.gz  404  Not Found [IP: 198.145.20.143 80]

E: Some index files failed to download, they have been ignored, or old ones used instead.
The command '/bin/sh -c apt-get update && apt-get install -y     curl     openjdk-6-jre' returned a non-zero code: 100
```

**Comment by sandroacoelho** [comment]
Hi @Palbear ,

You don't need to build it from scratch. We have pre-built images in Docker Hub to simplify everything. Just run 

```
docker run -i -p 2226:80 dbpedia/spotlight-german spotlight.sh
```


Anyway, I will check the Dockerfiles in order to fix this issue.

Best,

**Comment by Palbear** [comment]
Hi, thanks for answering me. 
Ok. I've tried that too and it says `listening on http://localhost:80/rest`
localhost:80/rest is not working and I've tried http://localhost:2226/rest, not working either.

**Comment by sandroacoelho** [comment]
Hi @Palbear ,

Once you have started Spotlight through Docker, try it

Annotate URL's
```
http://localhost:2226/rest/annotate?url=http://www.dw.com/de/keine-einsicht-in-nsa-spionageziele/a-36040102
```


Annotate Texts
```
http://localhost:2226/rest/annotate?text=Berlin ist die Hauptstadt von Deutschland
```

**Comment by pablomendes** [comment]
We should update the server startup console print message to help people to
run their first call, or update the ` GET /rest` to display some success
msg with pointers to the endpoints inside (`annotate`, `candidates`, etc)
