### ISSUE TITLE
Creating a DBpedia Spotlight runnable JAR after editing

### ISSUE THREAD

**Issue by marcopegoraro** [dbpedia-spotlight/dbpedia-spotlight#411]
Hi,
probably a very newbie question. I downloaded the source files of DBpedia Spotlight, compiled it, tested it, and I modified the behavior here and there. I'm having trouble creating a single runnable JAR from the whole project. Is the procedure to do that available somewhere?
Thanks,

Marco

**Comment by sandroacoelho** [comment]
Hi @marcopegoraro,

This question is covered by our documentation. Apologies for that.

Just run `mvn clean package`. Before some minutes you jar file will be available at /dist/target/dbpedia-spotlight-0.7-jar-with-dependencies.jar

Best,
