### ISSUE TITLE
Inconsistent results from Web Service and local service initiated with JAR

### ISSUE THREAD

**Issue by timstacey** [dbpedia-spotlight/dbpedia-spotlight#412]
Hi,
I'm getting much fewer and poorer quality results returned using the local version of spotlight with the JAR file compared to the Web Service, is there a way to enable the same model on the web service locally?

I downloaded the model that I'm currently using from here : http://spotlight.sztaki.hu/downloads/latest_models/en.tar.gz

Thank you!

**Comment by sandroacoelho** [comment]
Hi @timstacey ,

Please try http://www.dbpedia-spotlight.com/latest_models/en_2+2.tar.gz

Best,

**Comment by timstacey** [comment]
Rockin! 🎸  Thank you @sandroacoelho

**Comment by timstacey** [comment]
Just out of curiosity, is there somewhere that I can find out what distinguishes the 2+2 model?

**Comment by sandroacoelho** [comment]
@jodaiber: could you please give a hand on it?
