### ISSUE TITLE
french model archive is inconsistent

### ISSUE THREAD

**Issue by gooodmorningopenstack** [dbpedia-spotlight/dbpedia-spotlight#413]
Retrieved many times, the problem is reproductible.

```
* Connected to spotlight.sztaki.hu (193.225.89.3) port 80 (#0)
> GET /downloads/latest_models/fr.tar.gz HTTP/1.1
> User-Agent: curl/7.38.0
> Host: spotlight.sztaki.hu
> Accept: */*
> 
< HTTP/1.1 200 OK
< Date: Fri, 18 Nov 2016 15:52:43 GMT
* Server Apache/2.2.22 (Ubuntu) is not blacklisted
< Server: Apache/2.2.22 (Ubuntu)
< Last-Modified: Sun, 19 Jun 2016 23:01:05 GMT
< ETag: "48006c-17763000-535a9900543f5"
< Accept-Ranges: bytes
< Content-Length: 393621504
< Content-Type: application/x-gzip
```

```
tar xzvf fr.tar.gz 
fr/
fr/spotter_thresholds.txt
fr/model.properties
fr/fsa_dict.mem
fr/README.txt
fr/stopwords.list
fr/model/
fr/model/tokens.mem
fr/model/quantized_counts.mem
fr/model/sf.mem
fr/model/candmap.mem
fr/model/context.mem
fr/model/res.mem

gzip: stdin: unexpected end of file
tar: Unexpected EOF in archive
tar: Unexpected EOF in archive
tar: Error is not recoverable: exiting now
```

**Comment by RSamaium** [comment]
Same problem

**Comment by jodaiber** [comment]
Hi @gooodmorningopenstack @RSamaium,

did you observe this for the fr model only or for all of them? I can re-upload them in this case.

Jo

**Comment by RSamaium** [comment]
Fr model only

**Comment by jodaiber** [comment]
Hey, 

I reuploaded the `fr.tar.gz` file, please try again. If it doesn't work, you can also try the one from the archive.

Best,
Jo

**Comment by tiff** [comment]
@jodaiber I have the same issue described above with the german modal (``de.tar.gz``). Any chance that you can reupload it as well? Many thanks in advance

**Comment by gooodmorningopenstack** [comment]
On the side, you should add a SHA1 sum for every file to permit integrity checking.

**Comment by gooodmorningopenstack** [comment]
The french latest model is still corrupt for me (http://spotlight.sztaki.hu/downloads/latest_models/fr.tar.gz).
```
tar xvf fr.tar.gz 
fr/
fr/spotter_thresholds.txt
fr/model.properties
fr/fsa_dict.mem
fr/README.txt
fr/stopwords.list
fr/model/
fr/model/tokens.mem
fr/model/quantized_counts.mem
fr/model/sf.mem
fr/model/candmap.mem
fr/model/context.mem
fr/model/res.mem

gzip: stdin: unexpected end of file
tar: Unexpected EOF in archive
tar: Unexpected EOF in archive
tar: Error is not recoverable: exiting now

sha1sum fr.tar.gz 
019d79e1e8cf665e71aff2931e3c24c68d9fbda7  fr.tar.gz
```

**Comment by tiff** [comment]
It looks like even the english model (http://spotlight.sztaki.hu/downloads/latest_models/en.tar.gz) is affected.

**Comment by sandroacoelho** [comment]
Hi @tiff, @jodaiber 

We have transferred the models from staki.hu server to http://www.dbpedia-spotlight.com/ in December. Five days ago, I recompiled all [Docker images](https://hub.docker.com/r/dbpedia/) and got success except with the french model. 

Could you please the models from http://www.dbpedia-spotlight.com/latest_models/?

Best,

**Comment by tiff** [comment]
@sandroacoelho thanks for your response. I just tried what you suggested, same error:

```
root@foo:~# wget http://www.dbpedia-spotlight.com/latest_models/de.tar.gz
--2017-01-09 15:21:54--  http://www.dbpedia-spotlight.com/latest_models/de.tar.gz
Resolving www.dbpedia-spotlight.com (www.dbpedia-spotlight.com)... 200.131.17.29
Connecting to www.dbpedia-spotlight.com (www.dbpedia-spotlight.com)|200.131.17.29|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 592822272 (565M) [application/octet-stream]
Saving to: ‘de.tar.gz’

de.tar.gz                                    100%[=============================================================================================>] 565.36M  3.93MB/s    in 3m 8s

2017-01-09 15:25:03 (3.01 MB/s) - ‘de.tar.gz’ saved [592822272/592822272]

root@foo:~# tar xvf de.tar.gz
de/
de/spotter_thresholds.txt
de/model.properties
de/fsa_dict.mem
de/README.txt
de/stopwords.list
de/model/
de/model/tokens.mem
de/model/quantized_counts.mem
de/model/sf.mem
de/model/candmap.mem
de/model/context.mem
de/model/res.mem

gzip: stdin: unexpected end of file
tar: Unexpected EOF in archive
tar: Unexpected EOF in archive
tar: Error is not recoverable: exiting now
```

**Comment by sandroacoelho** [comment]
@tiff : you are right. Apologies for that. I have checked right now and our French, German, Dutch and Danish is not working as well.  Just English, Spanish, Italian, Portuguese, Hungarian, Swedish, Russian and Turkish is ok.

We need to regenerate and reupload it

**Comment by tiff** [comment]
@sandroacoelho thanks! I just tried to regenerate them myself by following the instructions at https://github.com/dbpedia-spotlight/model-quickstarter. Unfortunately I'm stuck at this error:

```
[INFO] Building wikistatsextractor 0.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[WARNING] The POM for org.dbpedia.spotlight:core:jar:0.7 is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.602 s
[INFO] Finished at: 2017-01-09T15:19:47+00:00
[INFO] Final Memory: 13M/609M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project wikistatsextractor: Could not resolve dependencies for project com.diffbot.wikistatsextractor:wikistatsextractor:jar:0.1-SNAPSHOT: Failure to find org.dbpedia.spotlight:core:jar:0.7 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced -> [Help 1]
```

Any chance that you can re-generate the corrupt models this week?

**Comment by sandroacoelho** [comment]
Seems that you have not org.dbpedia.spotlight:core:jar:0.7.  

I will try to fix it tonight and let you know.

Best,

**Comment by tiff** [comment]
Thank you!

**Comment by sandroacoelho** [comment]
Hi @tiff, cc:// all

We have fixed the French and German models. Both are available at [http://www.dbpedia-spotlight.com/latest_models/](http://www.dbpedia-spotlight.com/latest_models/).

In order to keep easy the regenerate process / delivery models process, we just made it available a docker that contains all tools to this dirty work.

Just run:

* docker run -it dbpediaspotlight/model-quickstarter 
* cd model-quickstarter/
* ./prepare.sh

 and then the command to the target model

EN - ./index_db.sh -b en/ignore.list wdir en_US en/stopwords.list English models/en
DE - ./index_db.sh -b de/ignore.list wdir de_DE de/stopwords.list German  models/de
NL -./index_db.sh -b nl/ignore.list wdir nl_NL nl/stopwords.list Dutch   models/nl
SV - ./index_db.sh -b sv/ignore.list wdir sv_SE sv/stopwords.list Swedish models/sv
PT - ./index_db.sh -b pt/ignore.list wdir pt_BR pt/stopwords.list Portuguese models/pt
FR - ./index_db.sh -b fr/ignore.list wdir fr_FR fr/stopwords.list French models/fr
ES - ./index_db.sh -b es/ignore.list wdir es_ES es/stopwords.list Spanish models/es
TR - ./index_db.sh -b tr/ignore.list wdir tr_TR tr/stopwords.list Turkish models/tr
NO - ./index_db.sh -b no/ignore.list wdir no_NO no/stopwords.list Norwegian models/no
IT -./index_db.sh wdir it_IT it/stopwords.list Italian models/it
DA -./index_db.sh wdir da_DK da/stopwords.list Danish models/da
JA - ./index_db.sh wdir ja_JP ja/stopwords.list None models/ja
CS - ./index_db.sh wdir cs_CZ cs/stopwords.list None models/cs
HU - ./index_db.sh wdir hu_HU hu/stopwords.list Hungarian models/hu
RU - ./index_db.sh wdir ru_RU ru/stopwords.list Russian models/ru
ZH - ./index_db.sh wdir zh_CN zh/stopwords.list None models/zh

**Comment by tiff** [comment]
Wow. Thanks for the great work!

**Comment by gooodmorningopenstack** [comment]
Thanks for the fix, I'll test it soon :+1:

**Comment by brandonhill** [comment]
I'm seeing this same dependency error for English:

```
[INFO] Building wikistatsextractor 0.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
Downloading: https://repo.maven.apache.org/maven2/org/dbpedia/spotlight/core/1.0/core-1.0.pom
[WARNING] The POM for org.dbpedia.spotlight:core:jar:1.0 is missing, no dependency information available
Downloading: https://repo.maven.apache.org/maven2/org/dbpedia/spotlight/core/1.0/core-1.0.jar
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.268 s
[INFO] Finished at: 2017-06-05T13:38:26-04:00
[INFO] Final Memory: 11M/245M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project wikistatsextractor: Could not resolve dependencies for project com.diffbot.wikistatsextractor:wikistatsextractor:jar:0.1-SNAPSHOT: Could not find artifact org.dbpedia.spotlight:core:jar:1.0 in central (https://repo.maven.apache.org/maven2) -> [Help 1]

```
