### ISSUE TITLE
Reference information contained in URI returned from spotlight

### ISSUE THREAD

**Issue by timstacey** [dbpedia-spotlight/dbpedia-spotlight#416]
Is there an easy way to get the entire set of information referenced in the URI from spotlight? For example, have the return payload contain all of the RDF triples instead of just the URI?

Thanks for making such an awesome project.

**Comment by sandroacoelho** [comment]
Hi @timstacey ,

You can do it using combining Spotlight results with  a triple store using sparql


Best,

**Comment by timstacey** [comment]
Sandro,
I'm sorry, would you mind elaborating just a bit more? I'm trying to figure out how I'd begin to accomplish this.

Thanks for the response!
- tim

**Comment by sandroacoelho** [comment]
Hi @timstacey. Happy new year. I will answer you tonight. Sorry for the big delay

**Comment by timstacey** [comment]
@sandroacoelho, sorry I gave up on this, and then I eventually figured it out - my solution is in python, was this along the lines of what you were thinking?

`from SPARQLWrapper import SPARQLWrapper, JSON

sparql = SPARQLWrapper("http://dbpedia.org/sparql")
sparql.setQuery("""
SELECT ?p ?o
WHERE 
  {
     <http://dbpedia.org/resource/Canberra>  ?p  ?o
  }
""")

sparql.setReturnFormat(JSON)
results = sparql.query().convert()`

where the returned URI is http://dbpedia.org/resource/Canberra

**Comment by sandroacoelho** [comment]
Hi @timstacey . Yes. You got it!

Sorry for not give a hand on this solution. I am in a rat race this month

Best,
