### ISSUE TITLE
Licensing status

### ISSUE THREAD

**Issue by timstacey** [dbpedia-spotlight/dbpedia-spotlight#423]
Howdy, I was wondering if anyone had an update on licensing - is this a full Apache system or is there still GPL involved?

**Comment by sandroacoelho** [comment]
Hi @timstacey ,

Still a small pending with Lingpipe (http://alias-i.com/lingpipe/licenses/lingpipe-license-1.txt). 
We can solve it into the next milestone.

Best,

**Comment by timstacey** [comment]
Ok thanks! 

Does that mean that the lingpipe dependency needs to be replaced? Just curious, also potentially interested in helping!

**Comment by sandroacoelho** [comment]
Yes. We need to replace that to get a 100% Apache License

**Comment by jodaiber** [comment]
LingPipe is not used in the current statistical backend, so it would only have to be replace for people interested in using the older Lucene backend.

**Comment by timstacey** [comment]
What's currently used in the containerized version for spotting?

**Comment by sandroacoelho** [comment]
statistical backend

**Comment by florentsolt** [comment]
Hi, any updates on that topic?
For sure having a 100% project will be awesome.

**Comment by sandroacoelho** [comment]
Hi @florentsolt ,

We are working on at Spotlight 0.8. This issue will be solved in this version. You can see our board [here](https://github.com/dbpedia-spotlight/dbpedia-spotlight/projects/1)

Best,

**Comment by florentsolt** [comment]
Thanks a lot for you answer.
Looking forward to it 😃

**Comment by sandroacoelho** [comment]
As announced in the last DBpedia newsletter, DBpedia Spotlight is now in the version 1.0 and is 100% Apache 2.0
So, we can close this issue. 

Thanks for your patience.
