### ISSUE TITLE
Broken models

### ISSUE THREAD

**Issue by idlefella** [dbpedia-spotlight/dbpedia-spotlight#425]
Some models hosted on http://spotlight.sztaki.hu/downloads/ seem to be broken. When I download for instance the latest_models/de.tar.gz, I get an error while extracting the archive with `tar xf de.tar.gz`:
```tar: Unexpected EOF in archive```

**Comment by sandroacoelho** [comment]
Hi @idlefella ,

Please try the models from http://www.dbpedia-spotlight.com/

**Comment by idlefella** [comment]
Hi @sandroacoelho 

Thanks for the hint. The models from http://www.dbpedia-spotlight.com/ work. Maybe the Wiki should be updated with the new link.

**Comment by sandroacoelho** [comment]
TODO: 
- [ ] Update wikilinks
