### ISSUE TITLE
Running DBpedia spotlight locally

### ISSUE THREAD

**Issue by Likhitha96** [dbpedia-spotlight/dbpedia-spotlight#430]
Hi,

I am trying to set DBpedia Spotlight locally using IntelliJ Idea. I have followed the instructions given in https://github.com/dbpedia-spotlight/dbpedia-spotlight/wiki/Setting-up-IntelliJ-IDEA and have successfully built it. However, when trying to run it, I am running into an error that says 
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 0
	at org.dbpedia.spotlight.web.rest.Server.main(Server.java:88)
How do i resolve this and how to test and run it locally?

**Comment by sandroacoelho** [comment]
Hi @Likhitha96 ,

Have you downloaded the models?

 - Model: model.dbpedia-spotlight.org or 
 - Lucene: lucene.dbpedia-spotlight.org

After it, you must fill in at Program Arguments 2 parameters for Model (language and url) 
  
Eg.:   en http://localhost:2222/rest

or 1 parameter for  Lucene server_2016-04.properties

Best
