### ISSUE TITLE
Raw data download

### ISSUE THREAD

**Issue by Likhitha96** [dbpedia-spotlight/dbpedia-spotlight#431]
Hi,

For our project, I would like to download raw data  to create entity extraction models. I tried downloading it from http://spotlight.sztaki.hu/downloads/raw/ but it just says that it is not found on server. Could you please suggest on where to download from?

Thanks in advance

**Comment by sandroacoelho** [comment]
Hi @Likhitha96 ,

Please try http://www.dbpedia-spotlight.com/latest_data/

Best,
