### ISSUE TITLE
Web service error

### ISSUE THREAD

**Issue by joseph6x** [dbpedia-spotlight/dbpedia-spotlight#432]
Hi,

I am calling the Spotlight Web Service (specifically the spanish model: http://model.dbpedia-spotlight.org/es/annotate ) from a local application for annotating some documents' summaries. The problem is that I am getting a odd error when the word 'sade' is included in the request text for instance: 'en el recinto valle del sade'. When such request is send the API returns a 400 response code and the following exception stack trace in the response body:

`org.dbpedia.spotlight.exceptions.OutputException: Error converting XML to JSON.Error converting XML to JSON.org.dbpedia.spotlight.web.rest.OutputManager.xml2json(OutputManager.java:236)org.dbpedia.spotlight.web.rest.SpotlightInterface.getJSON(SpotlightInterface.java:333)org.dbpedia.spotlight.web.rest.resources.Annotate.getJSON(Annotate.java:172)org.dbpedia.spotlight.web.rest.resources.Annotate.postJSON(Annotate.java:275)sun.reflect.GeneratedMethodAccessor15.invoke(Unknown Source)sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)java.lang.reflect.Method.invoke(Method.java:483)com.sun.jersey.spi.container.JavaMethodInvokerFactory$1.invoke(JavaMethodInvokerFactory.java:60)com.sun.jersey.server.impl.model.method.dispatch.AbstractResourceMethodDispatchProvider$ResponseOutInvoker._dispatch(AbstractResourceMethodDispatchProvider.java:205)com.sun.jersey.server.impl.model.method.dispatch.ResourceJavaMethodDispatcher.dispatch(ResourceJavaMethodDispatcher.java:75)com.sun.jersey.server.impl.uri.rules.HttpMethodRule.accept(HttpMethodRule.java:288)com.sun.jersey.server.impl.uri.rules.ResourceClassRule.accept(ResourceClassRule.java:108)com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147)com.sun.jersey.server.impl.uri.rules.RootResourceClassesRule.accept(RootResourceClassesRule.java:84)com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1469)com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1400)com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1349)com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1339)com.sun.jersey.spi.container.servlet.WebComponent.service(WebComponent.java:416)com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:537)com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:708)javax.servlet.http.HttpServlet.service(HttpServlet.java:853)com.sun.grizzly.http.servlet.ServletAdapter$FilterChainImpl.doFilter(ServletAdapter.java:1059)com.sun.grizzly.http.servlet.ServletAdapter$FilterChainImpl.invokeFilterChain(ServletAdapter.java:999)com.sun.grizzly.http.servlet.ServletAdapter.doService(ServletAdapter.java:434)com.sun.grizzly.http.servlet.ServletAdapter.service(ServletAdapter.java:379)com.sun.grizzly.tcp.http11.GrizzlyAdapter.service(GrizzlyAdapter.java:179)com.sun.grizzly.http.ProcessorTask.invokeAdapter(ProcessorTask.java:849)com.sun.grizzly.http.ProcessorTask.doProcess(ProcessorTask.java:746)com.sun.grizzly.http.ProcessorTask.process(ProcessorTask.java:1045)com.sun.grizzly.http.DefaultProtocolFilter.execute(DefaultProtocolFilter.java:228)com.sun.grizzly.DefaultProtocolChain.executeProtocolFilter(DefaultProtocolChain.java:137)com.sun.grizzly.DefaultProtocolChain.execute(DefaultProtocolChain.java:104)com.sun.grizzly.DefaultProtocolChain.execute(DefaultProtocolChain.java:90)com.sun.grizzly.http.HttpProtocolChain.execute(HttpProtocolChain.java:79)com.sun.grizzly.ProtocolChainContextTask.doCall(ProtocolChainContextTask.java:54)com.sun.grizzly.SelectionKeyContextTask.call(SelectionKeyContextTask.java:59)com.sun.grizzly.ContextTask.run(ContextTask.java:71)com.sun.grizzly.util.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:532)com.sun.grizzly.util.AbstractThreadPool$Worker.run(AbstractThreadPool.java:513)java.lang.Thread.run(Thread.java:745)`

I tried executing this request in the online demo and I got the same error.

Best,

**Comment by sandroacoelho** [comment]
Hi @joseph6x,
It seems a problem with encoding. I will check it ASAP

**Comment by sandroacoelho** [comment]
Dear @joseph6x ,

This issue was fixed today in our endpoint http://model.dbpedia-spotlight.org/es/annotate. 

Also it is available to download under http://downloads.dbpedia-spotlight.org/spotlight/ (dbpedia-spotlight-nightly-build.jar) and via Docker (latest)

Thank you for your patience,

``
{
    "@text": "en el recinto valle del sade",
    "@confidence": "0.5",
    "@support": "0",
    "@types": "",
    "@sparql": "",
    "@policy": "whitelist",
    "Resources": [
        {
            "@URI": "http://es.dbpedia.org/resource/Valle",
            "@support": "2043",
            "@types": "",
            "@surfaceForm": "valle",
            "@offset": "14",
            "@similarityScore": "0.9983354177612618",
            "@percentageOfSecondRank": "2.622101820426962E-4"
        },
        {
            "@URI": "http://es.dbpedia.org/resource/𐤑",
            "@support": "5",
            "@types": "",
            "@surfaceForm": "sade",
            "@offset": "24",
            "@similarityScore": "0.8346561761055059",
            "@percentageOfSecondRank": "0.0"
        }
    ]
}
``

**Comment by aleSuglia** [comment]
Seems that the only model that works is the English one. All the other are not working. Any ideas?

**Comment by jodaiber** [comment]
@sandroacoelho Did you have a look at the models, any idea why they are corrupted?

**Comment by sandroacoelho** [comment]
Dear @aleSuglia, @jodaiber ,

@aleSuglia: all services are available again. 

@jodaiber : so many restarts during an electrical maintenance at the weekend

Best,
