### ISSUE TITLE
406 when using text/xml - Wiki endpoints outdated!?

### ISSUE THREAD

**Issue by fr33g** [dbpedia-spotlight/dbpedia-spotlight#433]
I'm having some issues with the REST API. I'm trying to incorporate the UIMA wrapper into my pipeline. First I tried the api endpoint from the wiki (http://spotlight.dbpedia.org/rest/annotate). Apparently those do not exist anymore, since I'm getting a 404 consistently. Am I right to assume the wiki is outdated in terms of endpoint API? On the homepage though, I've found another endpoint (http://api.dbpedia-spotlight.org/annotate). In fact this one is working fine for me, when making requests with a rest console. However, I always get a 406 when using text/xml, which is again according to the wiki supported. It works with a application/json as well as with text/html. I wanted to double check with you, that the "old" endpoints are offline and the new ones do not support text/xml anymore, before adapting the UIMA component accordingly.

**Comment by sandroacoelho** [comment]
Hi @fr33g . Thank you for report this issue in our Wiki.I have just fixed.

Please use http://model.dbpedia-spotlight.org/<LANGUAGE>/annotate (E.g For English,  http://model.dbpedia-spotlight.org/en/annotate) . It supports text/xml.

[http://api.dbpedia-spotlight.org/annotate](https://github.com/dbpedia-spotlight/dbpedia-spotlight-services) is a draft proposal - we are testing some new approaches to produce annotations in new formats, features for language recognition etc. We will support text/xml soon.

Best,

**Comment by fr33g** [comment]
Thank you @sandroacoelho for the quick and helpful response! The endpoint you mentioned is working properly for me!
