### ISSUE TITLE
License clarification

### ISSUE THREAD

**Issue by meitals** [dbpedia-spotlight/dbpedia-spotlight#435]
How can I make sure to avoid using copyleft elements of the code?

**Comment by sandroacoelho** [comment]
Hi @meitals 

You can see about each library  licenses that we have been using in Spotlight [here](https://github.com/dbpedia-spotlight/dbpedia-spotlight/wiki/Licenses)

Best,

**Comment by meitals** [comment]
Thanks @sandroacoelho! So if I call `annotate`, should I assume that all those libraries are being used?

**Comment by sandroacoelho** [comment]
Not exactly. Our current endpoint is Apache 2.0
