### ISSUE TITLE
ERROR 2017-04-17 17:35:23,889 main [Db] - Method failed: HTTP/1.1 404 Not Found

### ISSUE THREAD

**Issue by TamouzeAssi** [dbpedia-spotlight/dbpedia-spotlight#438]
When i execute an example of dbpedia spotlight , i get the following error. Please see the following log:

INFO 2017-04-17 17:35:23,445 main [Db] - Querying API.
 INFO 2017-04-17 17:35:23,447 main [Db] - http://spotlight.sztaki.hu:2222/rest/annotaterest/annotate/?confidence=0.0&support=0&spotter=CoOccurrenceBasedSelector&disambiguator=Default&showScores=yes&powered_by=non&text=Is+the+Amazon+river+longer+than+the+Nile+River%3F
ERROR 2017-04-17 17:35:23,889 main [Db] - Method failed: HTTP/1.1 404 Not Found
Exception in thread "main" java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.LinkedList.checkElementIndex(Unknown Source)
	at java.util.LinkedList.get(Unknown Source)
	at spotlight.AnnotationClient.saveExtractedEntitiesSet(AnnotationClient.java:128)
	at spotlight.AnnotationClient.evaluateManual(AnnotationClient.java:148)
	at spotlight.AnnotationClient.evaluate(AnnotationClient.java:144)
	at spotlight.TestDriver.main(TestDriver.java:11)

Note that I use the jar spotlight and two classes:
1- public abstract class AnnotationClient
2- Db extends AnnotationClient:

    public class Db extends AnnotationClient {

    //private final static String API_URL = "http://jodaiber.dyndns.org:2222/";
    private static String  API_URL    = "http://spotlight.sztaki.hu:2222/";
    private static  double  CONFIDENCE = 0.0;
    private static  int     SUPPORT    = 0;
    private static  String  powered_by ="non";
    private static  String  spotter ="CoOccurrenceBasedSelector";
    //"LingPipeSpotter"=Annotate all spots 
    //AtLeastOneNounSelector"=No verbs and adjs.    
                                                //"CoOccurrenceBasedSelector" =No 'common words'
                                                //"NESpotter"=Only Per.,Org.,Loc.
    private static String  disambiguator ="Default";//Default ;Occurrences=Occurrence-centric;Document=Document-centric
    private static String  showScores ="yes";

    @SuppressWarnings("static-access")
    public void configiration(double CONFIDENCE,int SUPPORT,
                          String powered_by,String spotter,String disambiguator,String showScores){
    this.CONFIDENCE=CONFIDENCE;
    this.SUPPORT=SUPPORT;
    this.powered_by=powered_by;
    this.spotter=spotter;
    this.disambiguator=disambiguator;
    this.showScores=showScores;}
    public List<DBpediaResource> extract(Text text) throws AnnotationException {
        LOG.info("Querying API.");
        String spotlightResponse;
        try {
            String Query=API_URL + "rest/annotate/?" +
                    "confidence=" + CONFIDENCE
                  + "&support=" + SUPPORT
                  + "&spotter=" + spotter
                  + "&disambiguator=" + disambiguator
                  + "&showScores=" + showScores
                  + "&powered_by=" + powered_by
                  + "&text=" + URLEncoder.encode(text.text(), "utf-8");
            LOG.info(Query);

            GetMethod getMethod = new GetMethod(Query);
            getMethod.addRequestHeader(new Header("Accept", "application/json"));
            spotlightResponse = request(getMethod);

        } catch (UnsupportedEncodingException e) {
            throw new AnnotationException("Could not encode text.", e);
        }
        assert     spotlightResponse != null;
        JSONObject resultJSON         = null;
        JSONArray  entities           = null;

        try {                   
            resultJSON = new JSONObject(spotlightResponse);
            entities = resultJSON.getJSONArray("Resources");

        } catch (JSONException e) {
            //throw new AnnotationException("Received invalid response from DBpedia Spotlight API.");
        }

        LinkedList<DBpediaResource> resources = new LinkedList<DBpediaResource>();
        if(entities!=null) 
        for(int i = 0; i < entities.length(); i++) {
            try {
                JSONObject entity = entities.getJSONObject(i);
                resources.add(
                        new DBpediaResource(entity.getString("@URI"),
                        Integer.parseInt(entity.getString("@support"))));
            } catch (JSONException e) {
                LOG.error("JSON exception "+e);
            }
        }
        return resources;
    }}

Any help is appreciated please!

**Comment by sandroacoelho** [comment]
Hi @TamouzeAssi ,

Please change
```
private static String  API_URL    = "http://spotlight.sztaki.hu:2222/";
```

To

```
private static String  API_URL    = "http://model.dbpedia-spotlight.org/en/";
```

And 

```
String Query=API_URL + "rest/annotate/?" +
                "confidence=" + CONFIDENCE
              + "&support=" + SUPPORT
              + "&spotter=" + spotter
              + "&disambiguator=" + disambiguator
              + "&showScores=" + showScores
              + "&powered_by=" + powered_by
              + "&text=" + URLEncoder.encode(text.text(), "utf-8");
        LOG.info(Query);
```

To

```
String Query=API_URL + "rest/annotate/?" +
                "confidence=" + CONFIDENCE
              + "&text=" + URLEncoder.encode(text.text(), "utf-8");
        LOG.info(Query);
```

Best,

**Comment by TamouzeAssi** [comment]
Thanks for your reply and your hint. I modify the code but it still not working.

I call the Db class in the following way:
public class TestDriver {

	public static void main(String[] args) throws Exception {

	    String Question ="Is the Amazon river longer than the Nile River?";

	    Db c = new Db();  
	    c.configiration(0.0, 0, "non", "CoOccurrenceBasedSelector", "Default", "yes");
	    c.evaluate(Question);
	    System.out.println("resource : "+ c.getResu());
	}
  }

I get the following errors:
 INFO 2017-04-18 05:52:00,455 main [Db] - Querying API.
 INFO 2017-04-18 05:52:00,456 main [Db] - http://model.dbpedia-spotlight.org/en/rest/annotate/?confidence=0.0&text=Is+the+Amazon+river+longer+than+the+Nile+River%3F
ERROR 2017-04-18 05:52:01,203 main [Db] - Method failed: HTTP/1.1 404 Not Found
Exception in thread "main" java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.LinkedList.checkElementIndex(Unknown Source)
	at java.util.LinkedList.get(Unknown Source)
	at spotlight.AnnotationClient.saveExtractedEntitiesSet(AnnotationClient.java:128)
	at spotlight.AnnotationClient.evaluateManual(AnnotationClient.java:148)
	at spotlight.AnnotationClient.evaluate(AnnotationClient.java:144)
	at spotlight.TestDriver.main(TestDriver.java:11)

Thank you for your help

**Comment by TamouzeAssi** [comment]
Hi @sandroacoelho ,

The code is working without any modification. The problem was the .jar itself. After I change it, my code is running as I want.
 
My Last question please: 

How can I access the following variables:
@percentageOfSecondRank
@URI
@support
@surfaceForm
@offset
@similarityScore
@types

In another words, the function:

  public List<String> getResu(){ 	
    	        return RES;     
    }

Returns all the annotated entities.
The RES for the input question: 
String question ="Is the Amazon river longer than the Nile River? ";
is resource : [Isaiah, Amazon_River, Nile]

But How can I know (for example) the entity Amazon_River correspond for which word in question.
Thank you

**Comment by abcoep** [comment]
Hi @sandroacoelho 

Actually, the API URL

    http://model.dbpedia-spotlight.org:2222/

instead of

    http://model.dbpedia-spotlight.org/en/

works. Thanks!

**Comment by TamouzeAssi** [comment]
Thank you @abcoep.
