### ISSUE TITLE
error with the web service 

### ISSUE THREAD

**Issue by MohanadAlrefaai** [dbpedia-spotlight/dbpedia-spotlight#440]
I just want to ask if there is a temporary  problem in the server. 
I am using api url : http://spotlight.sztaki.hu:2222

I also tried to the demo and it didn't work.

can someone tell me what is the problem?

**Comment by sandroacoelho** [comment]
Hi @MohanadAlrefaai ,

Our new server is http://model.dbpedia-spotlight.org/en/annotate

Best,

**Comment by mr-uuid** [comment]
Hey @sandroacoelho, I'm seeing a `502 Bad Gateway` when accessing http://model.dbpedia-spotlight.org/en/annotate?text=Apple

Thanks for your help.

**Comment by sandroacoelho** [comment]
OMG :( 

 Could you please try again @mr-uuid ?

**Comment by mr-uuid** [comment]
Looks good, thanks @sandroacoelho !

**Comment by MohanadAlrefaai** [comment]
Thank you very much @sandroacoelho 
It is working  now :)

**Comment by christinedraper** [comment]
Thanks for the fast fix... works for me now

**Comment by danielhers** [comment]
Getting bad gateway on http://model.dbpedia-spotlight.org/en/annotate again...

**Comment by SamBelkacem** [comment]
I'm also getting bad gateway on http://model.dbpedia-spotlight.org/en/annotate. Do you have an alternative @danielhers, @sandroacoelho?

**Comment by danielhers** [comment]
Apart from waiting for it to be fixed or running my own local server, no.

**Comment by SamBelkacem** [comment]
Do you get the same results by running your own local server? I mean, what are the advantages of using this link http://model.dbpedia-spotlight.org/en/annotate against a local server?

**Comment by danielhers** [comment]
Well, the advantage is that you don't have to set it up yourself (which takes time and computing resources). I use it as the default in my deployed package.

**Comment by SamBelkacem** [comment]
Thank you for your answer @danielhers. Hope that the problem will be fixed soon ...

**Comment by kavin26** [comment]
I'm getting `HTTP 502 bad gateway` thrown when accessing http://model.dbpedia-spotlight.org/en/annotate for extracting entities from raw text.... planning to deploy it in production... is it better to for separate server for dbpedia or accessing http api? please give your suggestions

**Comment by kavin26** [comment]
seems to be solved by now... why is there such frequent glitches... i'm reconsidering it for deployment in my news recommendation application

**Comment by sandroacoelho** [comment]
Hi @kavin26. This is a demo server (has no such kind of important resources for production env such as failure recovery and redundancy ). I recommend you install your own server
