### ISSUE TITLE
results obtained by the jar are differents as those returned by demo

### ISSUE THREAD

**Issue by TamouzeAssi** [dbpedia-spotlight/dbpedia-spotlight#441]
Hello,

From one week ago the following link was working:
private static String  API_URL    = "http://spotlight.sztaki.hu:2222/";
and returns the same results as the demo spotlight dbpedia. 

From last Thursday and during the execution the connection is broken, and still till now.

Finally another API_URL  is given, which is: 
private static String  API_URL    = "http://model.dbpedia-spotlight.org:2222/";

But this API_URL didnt return the same results as before.

Can you please explain me why? and how can i get the same results?
Thank you

**Comment by sandroacoelho** [comment]
Hi @TamouzeAssi ,

model.dbpedia-spotlight.org/en have the same models that were running under spotlight.sztaki.hu:2222/ .
We have used scp in order to transfer all files from there, including configs, startups scripts etc.

Best,



Best,
