### ISSUE TITLE
Web Service (English model) returns connection refused error

### ISSUE THREAD

**Issue by tushkanova** [dbpedia-spotlight/dbpedia-spotlight#443]
I am calling the Spotlight Web Service (English - http://spotlight.sztaki.hu:2222/rest/annotate) from a local application and it seems that port 2222 is closed. 
Has the port for English been changed?

**Comment by sandroacoelho** [comment]
Hi @tushkanova ,

Please use http://model.dbpedia-spotlight.org/en/annotate/ instead

Best,
