### ISSUE TITLE
http://demo.dbpedia-spotlight.org/ not working 

### ISSUE THREAD

**Issue by vinayakbhat87** [dbpedia-spotlight/dbpedia-spotlight#446]
the annotation is not happening in http://demo.dbpedia-spotlight.org/

**Comment by sandroacoelho** [comment]
HI @vinayakbhat87 ,

Our **DEMO** service was unavailable for  2(two) hours to maintenance and it is up again.

You also can track the status of services at https://status.dbpedia-spotlight.org/

Thank you for your paticience,
