### ISSUE TITLE
GET vs POST performance differences?

### ISSUE THREAD

**Issue by snebel29** [dbpedia-spotlight/dbpedia-spotlight#450]
Hi,
I'm running a local instance of `dbpedia/spotlight-english:0.7.1` and sending some text to the `annotate` endpoint.

[The API documentation](http://www.dbpedia-spotlight.org/api) presents the interface for `annotate` with an example using `GET`, but `POST` is not mentioned anywhere.

I started playing with different texts, some of them higher than 8KB size, for those I was getting [response codes 414 URI is too long](https://httpstatuses.com/414), so I've decided to try using `POST`, the method seems accepted and the answer results are the same compared with the one requested using `GET` however I'm getting much slower answers which is weird.

You can reproduce the issue I'm getting by doing running spotlight 0.7.1 english instance using docker
```
$ sudo docker run -it -p 2222:80 dbpedia/spotlight-english:0.7.1 spotlight.sh
```
In a terminal (I've used bash) save the urlencoded text that will be used for both calls into a variable
```
text=iFixit%27s%20teardowns%20are%20handy%20disassembly%20guides%20and%20they%27re%20great%20for%20confirming%20just%20what%20hardware%20is%20included%20inside%20our%20gadgets%2C%20but%20most%20recent%20consumer%20electronics%20don%27t%20fare%20well%20when%20it%20comes%20time%20to%20assign%C2%A0a%C2%A0repairability%20score.%20Today%27s%20smartphones%20are%20typically%20held%20together%20with%20proprietary%20screws%20and%20a%20lot%20of%20glue%2C%20and%20while%20there%20are%20obvious%20user-facing%20benefits%20to%20this%20manufacturing%20approach%2C%20it%20tends%20to%20make%20the%20gadgets%20harder%20to%20open%2C%20upgrade%2C%20and%20repair.%0A%0AThat%27s%20not%20the%20case%20for%20the%20Fairphone%202%2C%20an%20Android%20phone%20built%20by%20a%20Dutch%20startup%20that%20makes%20repairability%20and%20serviceability%20one%20of%20its%20primary%20features.%20iFixit%20has%20torn%20down%20the%20phone%20using%20just%20human%20hands%20and%20a%20Phillips-head%20screwdriver%2C%20and%20has%20given%20the%20phone%20a%20rare%2010%20out%20of%2010%20on%20its%20repairability%20scale%20because%20of%20how%20easy%20it%20is%20for%20users%20to%20open%20and%20fix.%20The%20battery%20and%20the%20screen%E2%80%94two%20components%20that%20will%20most%20need%20to%20be%20replaced%20or%20repaired%20over%20the%20lifetime%20of%20the%20phone%E2%80%94pop%20out%20without%20any%20tools%20at%20all.%20Removing%20the%20modules%20for%20the%20camera%2C%20microphone%2C%20and%20headphone%20jack%20isn%27t%20much%20more%20difficult.%0A%0ADespite%20that%20perfect%20score%2C%20there%20is%20one%20mark%20against%20the%20Fairphone%202.%20The%20front%20glass%20and%20the%20LCD%20panel%20are%20fused%20together%2C%20which%20makes%20the%20screen%20look%20better%20but%20increases%20the%20cost%20of%20fixing%20it%20since%20you%20need%20to%20replace%20the%20glass%20and%20the%20LCD%20even%20if%20you%20only%20break%20one%20of%20them.%20This%20is%20a%20common%20iFixit%20bugaboo%20going%20all%20the%20way%20back%20to%20the%20days%20of%20the%20iPhone%205%2C%20and%20why%20it%20didn%27t%20knock%20points%20off%20the%20score%C2%A0is%20anybody%27s%20guess.%0A%0AThe%20Fairphone%202%20is%20launching%20primarily%20in%20Europe%20to%20start%2C%20and%20will%20sell%C2%A0for%20a%20relatively%20steep%C2%A0%E2%82%AC525%20%28about%20%24560%29.%20It%27s%20aimed%20primarily%20at%20those%20who%20value%20repairability%20above%20all%20else.%20Its%20specs%20aren%27t%20bad%E2%80%94it%27s%20got%20a%205-inch%201080p%20screen%2C%20a%20Snapdragon%20801%20SoC%2C%202GB%20of%20RAM%2C%20and%20Android%205.1%E2%80%94but%20it%20has%C2%A0a%20lot%20in%20common%20with%20flagship%20Android%20phones%20from%20early%202014.%20The%20phone%20is%20also%20noticeably%20bulkier%20than%20more%20mainstream%20phones%20with%20similar%20specs%20and%20screens.%20For%20reference%2C%20the%20OnePlus%20X%20makes%20you%20deal%20with%20OnePlus%27%20frustrating%20invite%20system%20and%20gives%20up%20any%20semblance%20of%20easy%20repairability%2C%20but%20it%20includes%20similar%20specs%20for%20less%20than%20half%20the%20price.
```
In the same terminal session run the following curl commands together (multiple times) so you avoid the initial warm-up delay I noticed
```
curl -vvv -H "accept: application/json" -w "%{http_code} %{time_total} " -X GET http://localhost:2222/rest/annotate?text=${text}
curl -vvv -H "accept: application/json" -w "%{http_code} %{time_total} " -X POST http://localhost:2222/rest/annotate -d text=${text}
```
Time spent time will shown at the end, after the status_code which for the `GET` request is around 100ms and for the `POST` one is above 1000ms.

The only obvious differences I can see are the way the data is send, both send the urlencoded string but `GET` does it as a URI parameter and `POST` into the body adding `application/x-www-form-urlencoded` header, results except for the huger time different seems to be exactly the same.

Log analysis and tcpdump confirm that the post request spend around 1 second to be returned in the case of the `POST` request

- Is there anything I'm missing here?
- Do you have an explanation for such a huge processing time difference?

I could provide further details if needed.

Thanks!

**Comment by snebel29** [comment]
Does anybody else see the same pattern?

**Comment by Skunnyk** [comment]
Hi,

I can reproduce your behavior. It's due to the "100-continue" header ( https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/100 ) . 
In POST requests, curl send a "Expect: 100 continue" header and wait before sending the body. Grizzly seems to be slow to answer this 100 request, so it slow down the process.
I never noticed that because I use nginx as a reverse proxy behind spotlight. Nginx answer the "Expect:" header himself (see http://nginx.org/en/docs/http/ngx_http_proxy_module.html ) before passing it to spotlight, so the performance problem does not occur.

You can use your curl request with an empty Expect header ( -H "Expect:" ), and spotlight should answer immediatly.

**Comment by snebel29** [comment]
Nice catch! thank you for the answer... :-)
