### ISSUE TITLE
Install dpedia-spotlight

### ISSUE THREAD

**Issue by TamouzeAssi** [dbpedia-spotlight/dbpedia-spotlight#452]
Hello,

I have a question on how to I can use dbpedia-spotlight on my pc. In another words, instead I call the web-service in my code using the API_URL like in the following:

```
public class DbSpotlightClient extends DbAnnotationClient {

	private  String  API_URL    = "http://model.dbpedia-spotlight.org/en/annotate";
	List<ResourceItem>resources;
	public List<ResourceItem> extract(String text)throws AnnotationException{
	...
  }
}
```

So, how can ,instead of calling this remote web service,  call this web service as a local service? In another words, instead the above API_URL, can i modify the API_URL TO BE 
`private String API_URL = "http://localhost:2222/rest."` (or something else);

How i can do that?

I want to do that, because I have a huge file which i want to annotate the text inside. And every time i call the web service, it stops to answer (exception) after several hours due to overlaod questions or a connection error!

Any suggestion is appreciated.

PS: the link in `https://github.com/dbpedia-spotlight/dbpedia-spotlight/wiki/Downloads` concerning the data is all broken.
Thanks for your advices

**Comment by sandroacoelho** [comment]
Hi @TamouzeAssi ,

Just use `` private String API_URL = "http://localhost:2222/rest/annotate"; `` instead of ``private  String  API_URL    = "http://model.dbpedia-spotlight.org/en/annotate" ``

Best,
