### ISSUE TITLE
en-spotlight server is down

### ISSUE THREAD

**Issue by AgoloKennethTan** [dbpedia-spotlight/dbpedia-spotlight#457]
![image](https://user-images.githubusercontent.com/30807189/32412206-b5838048-c1c6-11e7-80a7-9611c8e062e2.png)

**Comment by sandroacoelho** [comment]
Dear @AgoloKennethTan , 

It is available again. Sorry for that.

Best,

**Comment by AgoloKennethTan** [comment]
Thanks man! Great y'all are doing by the way!
