### ISSUE TITLE
Missing too much jars

### ISSUE THREAD

**Issue by QSmile** [dbpedia-spotlight/dbpedia-spotlight#458]
I import dbpedia-spotlight-model as maven project. But there are so much jars can not been find:

Missing artifact edu.umd:cloud9:jar:SNAPSHOT
Missing artifact edu.umd:cloud9:jar:SNAPSHOT
Missing artifact edu.umd:cloud9:jar:SNAPSHOT
Missing artifact javax.sql:jdbc-stdext:jar:2.0
Missing artifact javax.sql:jdbc-stdext:jar:2.0
Missing artifact javax.sql:jdbc-stdext:jar:2.0
Missing artifact javax.transaction:jta:jar:1.0.1B
Missing artifact javax.transaction:jta:jar:1.0.1B
Missing artifact javax.transaction:jta:jar:1.0.1B
Missing artifact jdbm:jdbm:jar:3.0-SNAPSHOT
Missing artifact jdbm:jdbm:jar:3.0-SNAPSHOT
Missing artifact jdbm:jdbm:jar:3.0-SNAPSHOT
Missing artifact jdk.tools:jdk.tools:jar:1.8
Missing artifact jdk.tools:jdk.tools:jar:1.8
Missing artifact jdk.tools:jdk.tools:jar:1.8
Missing artifact opennlp:maxent:jar:3.0.0
Missing artifact opennlp:maxent:jar:3.0.0
Missing artifact opennlp:maxent:jar:3.0.0
Missing artifact org.restlet.jee:org.restlet:jar:2.3.0
Missing artifact org.restlet.jee:org.restlet:jar:2.3.0
Missing artifact org.restlet.jee:org.restlet:jar:2.3.0
Missing artifact org.restlet.jee:org.restlet.ext.servlet:jar:2.3.0
Missing artifact org.restlet.jee:org.restlet.ext.servlet:jar:2.3.0
Missing artifact org.restlet.jee:org.restlet.ext.servlet:jar:2.3.0
Missing artifact org.semanticweb.yars:nxparser:jar:1.1
Missing artifact org.semanticweb.yars:nxparser:jar:1.1
Missing artifact org.semanticweb.yars:nxparser:jar:1.1
Missing artifact scala.ahocorasick:spotter-aho:jar:0.1
Missing artifact scala.ahocorasick:spotter-aho:jar:0.1
Missing artifact scala.ahocorasick:spotter-aho:jar:0.1
Missing artifact weka:kea-goss-weka:jar:5.0-SNAPSHOT
Missing artifact weka:kea-goss-weka:jar:5.0-SNAPSHOT
Missing artifact weka:kea-goss-weka:jar:5.0-SNAPSHOT
Missing artifact weka:weka:jar:3.7.3
Missing artifact weka:weka:jar:3.7.3
Missing artifact weka:weka:jar:3.7.3
Project: "index" in scope: "main" not built due to errors in dependent project(s): core. Root error(s): The project cannot be built until build path errors are resolved
Project: "rest" in scope: "main" not built due to errors in dependent project(s): core. Root error(s): The project cannot be built until build path errors are resolved
Project: "rest" in scope: "tests" not built due to errors in dependent project(s): core. Root error(s): The project cannot be built until build path errors are resolved
The container 'Maven Dependencies' references non existing library 'E:\m2repository\javax\sql\jdbc-stdext\2.0\jdbc-stdext-2.0.jar'
The container 'Maven Dependencies' references non existing library 'E:\m2repository\javax\sql\jdbc-stdext\2.0\jdbc-stdext-2.0.jar'
The container 'Maven Dependencies' references non existing library 'E:\m2repository\javax\sql\jdbc-stdext\2.0\jdbc-stdext-2.0.jar'
The project cannot be built until build path errors are resolved

**Comment by sandroacoelho** [comment]
Hi @QSmile ,

Could you please use https://github.com/dbpedia-spotlight/dbpedia-spotlight-model instead?

Thanks
