### ISSUE TITLE
[Feature] Multiple Index Files for Download

### ISSUE THREAD

**Issue by pablomendes** [dbpedia-spotlight/dbpedia-spotlight#48]
Converted from [SourceForge issue 3505376](http://sourceforge.net/support/tracker.php?aid=3505376), submitted by pablomendes

We could provide, besides the small and large indexes, some more topical splits. Either by 
- type: Person, Location, Organization. 
- subject: based on Wikipedia categories
- different sections of the power-law distribution (let's say in 10 splits, and let the users choose which to load).

**Comment by sandroacoelho** [comment]
This issue is not valid anymore. We will replace Lucene in a new version.
