### ISSUE TITLE
[Feature] Upgrade to latest lucene

### ISSUE THREAD

**Issue by pablomendes** [dbpedia-spotlight/dbpedia-spotlight#51]
Converted from [SourceForge issue 3520279](http://sourceforge.net/support/tracker.php?aid=3520279), submitted by pablomendes

A year ago we downgraded our Lucene in order to match the lowest common denominator between all libraries we had. Now libraries have updated, and we have dropped a few of them. It's time to go to the latest lucene. This may require changing quite a few of the core classes that depend on Lucene behavior.

**Comment by sandroacoelho** [comment]
This issue is not valid anymore. We will replace Lucene in a new version.
