### ISSUE TITLE
Encoding problems

### ISSUE THREAD

**Issue by pablomendes** [dbpedia-spotlight/dbpedia-spotlight#9]
Converted from [SourceForge issue 3315418](http://sourceforge.net/support/tracker.php?aid=3315418), submitted by pablomendes

There seem to be a few characters that make a search to Lucene never finish. We need good test cases and the correct escape/clean functions.
The text in this page makes it hang forever, for example:
http://supplesoftware.wordpress.com/2009/07/01/make-sure-you-get-all-your-messages-in-your-scala-code/ 

While doing that, also check for receiving encoded URIs to make it easier for clients (e.g. in Javascript). Server side would have to accept encoded parameters, decode them, perform annotation and encode the text again before sending response

**Comment by tgalery** [comment]
what about Goose https://github.com/GravityLabs/goose ?

**Comment by sandroacoelho** [comment]
Hey @tgalery We can use goose in our new version :+1:
