### ISSUE TITLE
i18n AllOccurrenceSource

### ISSUE THREAD

**Issue by pablomendes** [dbpedia-spotlight/dbpedia-spotlight#97]
I have just asked @sandroacoelho if he could take a stab at internationalizing the AllOccurrenceSource which still has some hacks to remove articles (the, a) and parenthesis with "disambiguation" from the article titles.

@maxjakob, can you please help us make sure that we don't break anything badly when doing this? Can we get this "disambiguation" string from the blacklistedURIs file? Any suggestions on how to go about this?

Example points where changes are needed: [L91](https://github.com/dbpedia-spotlight/dbpedia-spotlight/blob/master/index/src/main/scala/org/dbpedia/spotlight/io/AllOccurrenceSource.scala#L91),  [L134](https://github.com/dbpedia-spotlight/dbpedia-spotlight/blob/master/index/src/main/scala/org/dbpedia/spotlight/io/AllOccurrenceSource.scala#L134), etc.

**Comment by sandroacoelho** [comment]
Fixed at https://github.com/sandroacoelho/lucene-quickstarter
